export function withContextUi(html) {
  if (typeof html !== "string") return html;
  const extension = `
<style>
  .ctx-mini{margin-top:9px;padding-top:9px;border-top:1px solid rgba(255,255,255,.06)}
  .ctx-mini-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:6px}
  .ctx-mini-title{font-size:8px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:#718091}.ctx-mini-note{font-size:8px;color:#5f6d7a}
  .ctx-observation{display:flex;align-items:flex-start;gap:6px;font-size:9px;line-height:1.35;color:#a4b0bc;margin-top:4px}.ctx-dot{width:6px;height:6px;border-radius:50%;margin-top:3px;flex:0 0 auto;background:#718091}.ctx-observation.warning .ctx-dot{background:#f1c84b}.ctx-observation.supporting .ctx-dot{background:#72dc66}.ctx-observation.interesting .ctx-dot{background:#4ca6ff}
  .ctx-detail-source{font-size:9px;color:#6f7e8d;line-height:1.45;margin-top:10px}.ctx-venue{font-size:12px;font-weight:850;margin-bottom:8px}.ctx-sub{color:#8c9aaa;font-size:10px;line-height:1.45}
  .ctx-compare{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.ctx-side{border:1px solid rgba(255,255,255,.06);background:#121a24;border-radius:10px;padding:9px}.ctx-side strong{font-size:12px}.ctx-row{display:flex;justify-content:space-between;gap:8px;font-size:9px;color:#8c9aaa;margin-top:5px}.ctx-row b{color:#d9e3ec;font-weight:850}
  .ctx-quality{margin-top:10px;border:1px solid rgba(255,255,255,.06);background:#0b1118;border-radius:10px;padding:9px}.ctx-quality-head{display:flex;justify-content:space-between;gap:8px;font-size:10px;font-weight:850}.ctx-quality-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px 10px;margin-top:7px}.ctx-check{font-size:9px;color:#8c9aaa}.ctx-check.ok{color:#9bdc91}.ctx-check.miss{color:#d7a7a7}
  .ctx-source-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:10px}.ctx-source{border:1px solid rgba(255,255,255,.06);background:#121a24;border-radius:9px;padding:8px;font-size:9px}.ctx-source strong{display:block;margin-bottom:3px}.ctx-source.ok{color:#9bdc91}.ctx-source.bad{color:#ff9b9b}.ctx-source.warn{color:#f1c84b}.ctx-source small{color:#7f8d9c;display:block;line-height:1.35}
  .ctx-sync-banner{margin-top:8px;border-radius:10px;padding:8px 9px;font-size:9px;font-weight:800}.ctx-sync-banner.busy{background:rgba(76,166,255,.1);color:#6cb7ff}.ctx-sync-banner.ok{background:rgba(114,220,102,.1);color:#8de580}.ctx-sync-banner.bad{background:rgba(255,126,126,.1);color:#ff9b9b}
</style>
<script>
(function(){
  var ctxData=null,ctxKey='',loading=false;
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
  function num(v,suffix){var n=Number(v);return Number.isFinite(n)?(Math.round(n*10)/10)+(suffix||''):'—'}
  function rec(m){if(!m)return '—';var total=(m.wins||0)+(m.losses||0)+(m.ties||0);if(!total)return '0-0';return (m.wins||0)+'-'+(m.losses||0)+(m.ties?'-'+m.ties:'')}
  function findGame(away,home){return ctxData&&ctxData.games&&ctxData.games.find(function(g){return g.awayCode===away&&g.homeCode===home})}
  function obsHtml(o){return '<div class="ctx-observation '+esc(o.kind)+'"><span class="ctx-dot"></span><span><strong>'+esc(o.label)+':</strong> '+esc(o.detail)+'</span></div>'}
  function miniHtml(g){var obs=(g.observations||[]).slice(0,3);if(!obs.length)return '';return '<div class="ctx-mini"><div class="ctx-mini-head"><span class="ctx-mini-title">Context</span><span class="ctx-mini-note">does not change %</span></div>'+obs.map(obsHtml).join('')+'</div>'}
  function sourceClass(status){return status==='matched'?'ok':status==='failed'?'bad':status==='not-imported'?'warn':'warn'}
  function sourceLabel(status){return status==='matched'?'✅ matched':status==='failed'?'❌ failed':status==='not-imported'?'○ not imported':'⚠ unmatched'}
  function dataQuality(g){var q=g.quality||{loaded:0,total:0,checks:[]};return '<div class="ctx-quality"><div class="ctx-quality-head"><span>Data Quality</span><span>'+esc(q.loaded)+'/'+esc(q.total)+' fields loaded</span></div><div class="ctx-quality-grid">'+(q.checks||[]).map(function(c){return '<div class="ctx-check '+(c.ok?'ok':'miss')+'">'+(c.ok?'✅ ':'❌ ')+esc(c.label)+' <span style="color:#657382">· '+esc(c.source)+'</span></div>'}).join('')+'</div></div>'}
  function detailHtml(g){
    var w=g.weather||{},a=g.awayMetrics,h=g.homeMetrics;
    var venue=[g.stadium,g.roof,g.surface].filter(Boolean).join(' · ')||'Venue details not loaded';
    var weather=[Number.isFinite(Number(w.temperatureF))?Math.round(w.temperatureF)+'°F':null,Number.isFinite(Number(w.windMph))?Math.round(w.windMph)+' mph wind':null,Number.isFinite(Number(w.precipitationProbability))?Math.round(w.precipitationProbability)+'% precip':null].filter(Boolean).join('');
    var weatherStatus=w&&w.fetchedAt?'✅ loaded':'⚠ unavailable';
    return '<section class="detail-card ctx-detail"><h3>Context Intelligence</h3><div class="ctx-venue">'+esc(venue)+'</div><div class="ctx-sub">'+esc(weather||'Kickoff forecast not loaded')+'</div>'+
      '<div class="ctx-source-grid"><div class="ctx-source '+sourceClass(g.sourceStatus&&g.sourceStatus.nflverse)+'"><strong>nflverse</strong>'+sourceLabel(g.sourceStatus&&g.sourceStatus.nflverse)+'<small>venue · rest · coach · QB</small></div><div class="ctx-source '+sourceClass(g.sourceStatus&&g.sourceStatus.nfldata)+'"><strong>nfldata</strong>'+sourceLabel(g.sourceStatus&&g.sourceStatus.nfldata)+'<small>game context · team metrics</small></div><div class="ctx-source '+(w&&w.fetchedAt?'ok':'warn')+'"><strong>Open-Meteo</strong>'+weatherStatus+'<small>'+(w&&w.fetchedAt?'fetched '+esc(w.fetchedAt):'kickoff weather')+'</small></div></div>'+
      (g.observations||[]).map(obsHtml).join('')+
      '<div class="ctx-compare"><div class="ctx-side"><strong>'+esc(g.awayCode)+'</strong><div class="ctx-row"><span>Record</span><b>'+esc(rec(a))+'</b></div><div class="ctx-row"><span>Point diff</span><b>'+esc(a&&a.pointDiff!=null?(a.pointDiff>0?'+':'')+a.pointDiff:'—')+'</b></div><div class="ctx-row"><span>Off EPA</span><b>'+esc(num(a&&a.offensiveEpa,''))+'</b></div><div class="ctx-row"><span>Success</span><b>'+esc(num(a&&a.successRate,'%'))+'</b></div><div class="ctx-row"><span>Rest</span><b>'+esc(g.awayRest==null?'—':g.awayRest+'d')+'</b></div><div class="ctx-row"><span>Coach</span><b>'+esc(g.awayCoach||'—')+'</b></div><div class="ctx-row"><span>QB</span><b>'+esc(g.awayQb||'—')+'</b></div></div><div class="ctx-side"><strong>'+esc(g.homeCode)+'</strong><div class="ctx-row"><span>Record</span><b>'+esc(rec(h))+'</b></div><div class="ctx-row"><span>Point diff</span><b>'+esc(h&&h.pointDiff!=null?(h.pointDiff>0?'+':'')+h.pointDiff:'—')+'</b></div><div class="ctx-row"><span>Off EPA</span><b>'+esc(num(h&&h.offensiveEpa,''))+'</b></div><div class="ctx-row"><span>Success</span><b>'+esc(num(h&&h.successRate,'%'))+'</b></div><div class="ctx-row"><span>Rest</span><b>'+esc(g.homeRest==null?'—':g.homeRest+'d')+'</b></div><div class="ctx-row"><span>Coach</span><b>'+esc(g.homeCoach||'—')+'</b></div><div class="ctx-row"><span>QB</span><b>'+esc(g.homeQb||'—')+'</b></div></div></div>'+
      dataQuality(g)+'<div class="ctx-detail-source">Context synced: '+esc(g.contextSyncedAt||'never')+'. Sources are shown above. Context is informational only and never alters the spread or Survivor probability.</div></section>'
  }
  function decorate(){if(!ctxData)return;document.querySelectorAll('.game-card').forEach(function(card){if(card.querySelector('.ctx-mini'))return;var codes=[].map.call(card.querySelectorAll('.team-code'),function(n){return n.textContent.trim()});if(codes.length>=2){var g=findGame(codes[0],codes[1]);if(g)card.insertAdjacentHTML('beforeend',miniHtml(g))}});var detail=document.querySelector('.detail-content');if(detail&&!detail.querySelector('.ctx-detail')){var heroes=[].map.call(document.querySelectorAll('.detail .hero-code'),function(n){return n.textContent.trim()});if(heroes.length>=2){var g=findGame(heroes[0],heroes[1]);if(g){var kick=detail.querySelector('.kickoff');if(kick)kick.insertAdjacentHTML('afterend',detailHtml(g));else detail.insertAdjacentHTML('afterbegin',detailHtml(g))}}}addToolButton()}
  async function ensureData(){if(loading)return;loading=true;try{var d=await fetch('/api/dashboard/nfl',{cache:'no-store'}).then(function(r){return r.json()});if(!d||!d.season||!d.week)return;var key=d.season+'-'+d.week;if(ctxData&&ctxKey===key){decorate();return}var r=await fetch('/api/context/nfl?season='+encodeURIComponent(d.season)+'&week='+encodeURIComponent(d.week),{cache:'no-store'});if(r.ok){ctxData=await r.json();ctxKey=key;decorate()}}catch(e){}finally{loading=false}}
  function addToolButton(){var section=[].find.call(document.querySelectorAll('.section'),function(s){return /Manual Actions/i.test(s.textContent||'')});if(!section||section.querySelector('[data-context-sync]'))return;var b=document.createElement('button');b.className='tool-action';b.setAttribute('data-context-sync','1');b.innerHTML='<span class="tool-icon">◇</span><span><span class="tool-name">Update Context</span><span class="tool-desc">Refresh nflverse, nfldata and kickoff weather. Free context data; does not change picks.</span><span class="ctx-sync-status" data-context-status>Ready</span></span><span class="chev">›</span>';b.addEventListener('click',runSync);var actions=section.querySelectorAll('.tool-action');if(actions.length)actions[actions.length-1].insertAdjacentElement('afterend',b);else section.appendChild(b)}
  function summaryText(b){var d=b&&b.diagnostics||{};var nv=d.nflverse||{},ng=d.nfldataGames||{},ns=d.nfldataTeamStats||{},om=d.openMeteo||{};return '✅ Context Update Complete\n\nStored games: '+(d.storedGames||0)+'\nnflverse: '+(nv.matchedGames||0)+'/'+(d.storedGames||0)+' matched · '+(nv.rowsReturned||0)+' rows\nnfldata games: '+(ng.matchedGames||0)+'/'+(d.storedGames||0)+' matched · '+(ng.rowsReturned||0)+' rows\nnfldata team stats: '+(ns.teamsWithAdvancedMetrics||0)+' teams with advanced metrics · '+(ns.sourceRows||0)+' rows\nOpen-Meteo: '+(om.forecastsStored||0)+' forecasts stored · '+(om.skippedOrUnavailable||0)+' unavailable\n\nUnmatched nflverse: '+((nv.unmatchedGames||[]).join(', ')||'none')+'\nUnmatched nfldata: '+((ng.unmatchedGames||[]).join(', ')||'none')+((b.errors&&b.errors.length)?'\n\nErrors:\n- '+b.errors.join('\n- '):'')}
  async function runSync(ev){var btn=ev.currentTarget,out=document.getElementById('toolResult'),status=btn.querySelector('[data-context-status]');btn.disabled=true;if(status)status.textContent='⏳ Updating Context…';if(out)out.textContent='⏳ Updating Context Intelligence…';try{var d=await fetch('/api/dashboard/nfl',{cache:'no-store'}).then(function(r){return r.json()});var r=await fetch('/api/context/sync?season='+encodeURIComponent(d.season)+'&week='+encodeURIComponent(d.week),{method:'POST',credentials:'same-origin'});var b=await r.json();if(!r.ok)throw new Error(b.message||b.error||'Context update failed');if(status)status.textContent='✅ Context Updated';if(out)out.textContent=summaryText(b);ctxData=null;ctxKey='';await ensureData()}catch(e){if(status)status.textContent='❌ Context Update Failed';if(out)out.textContent='❌ Context Update Failed\n'+e.message}finally{btn.disabled=false}}
  new MutationObserver(function(){decorate();ensureData()}).observe(document.documentElement,{childList:true,subtree:true});
  ensureData();
})();
</script>`;
  return html.replace("</body>", `${extension}\n</body>`);
}
