export function withSurvivorV012Ui(html) {
  if (typeof html !== "string") return html;
  const extension = `
<style>
  .s12-overlay{position:fixed;inset:0;z-index:120;background:#080b10;color:#f4f7fb;overflow:auto;padding-bottom:92px;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}
  .s12-head{position:sticky;top:0;z-index:5;display:flex;align-items:center;gap:10px;padding:calc(13px + env(safe-area-inset-top)) 14px 12px;background:rgba(8,11,16,.97);border-bottom:1px solid rgba(255,255,255,.07)}
  .s12-back{border:0;background:transparent;color:#e8eef4;font-size:28px;width:36px;height:36px;cursor:pointer}.s12-title{font-size:14px;font-weight:950}.s12-sub{font-size:10px;color:#8795a5;margin-top:2px}
  .s12-body{max-width:760px;margin:0 auto;padding:14px}.s12-loading,.s12-error{border:1px dashed #263444;border-radius:15px;padding:26px;text-align:center;color:#8c9aaa;font-size:12px}
  .s12-entries{display:flex;gap:7px;overflow:auto;padding-bottom:3px;margin-bottom:12px}.s12-entry{white-space:nowrap;border:1px solid #263444;background:#0d141c;color:#91a0af;border-radius:999px;padding:8px 11px;font-size:10px;font-weight:900;cursor:pointer}.s12-entry.active{background:#4ca6ff;color:#06111b;border-color:#4ca6ff}
  .s12-command{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:12px}.s12-entry-card{border:1px solid #202d3c;background:#0d131b;border-radius:13px;padding:10px;min-width:0}.s12-entry-name{font-size:10px;font-weight:900;color:#91a0af}.s12-entry-pick{font-size:13px;font-weight:950;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s12-entry-meta{font-size:9px;color:#687788;margin-top:3px}
  .s12-strategy{border:1px solid #263444;background:#0d141c;border-radius:15px;padding:12px 13px;margin-bottom:12px}.s12-strategy-title{font-size:10px;color:#8c9aaa;font-weight:900;text-transform:uppercase;letter-spacing:.04em}.s12-strategy-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:8px}.s12-strategy-label{font-size:9px;color:#718091;font-weight:850}.s12-strategy-team{font-size:17px;font-weight:950;margin-top:2px}.s12-strategy-meta{font-size:10px;color:#9aa8b6;margin-top:3px;line-height:1.35}.s12-reason{font-size:9px;color:#7f8d9b;margin-top:5px;line-height:1.35}
  .s12-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:4px 0 10px}.s12-count{font-size:10px;color:#8c9aaa;font-weight:800}.s12-sort{border:1px solid #263444;background:#0e151e;color:#f4f7fb;border-radius:10px;padding:8px 10px;font-size:10px;font-weight:850;min-height:38px}
  .s12-note{font-size:9px;line-height:1.45;color:#778696;margin:0 2px 11px}.s12-card{border:1px solid #223041;background:#0e141c;border-radius:15px;padding:13px 14px;margin-bottom:9px}.s12-card.used{opacity:.55}.s12-card.selected{border-color:#4ca6ff}.s12-main{display:grid;grid-template-columns:86px minmax(0,1fr) auto;gap:13px;align-items:start}.s12-rank{font-size:9px;color:#6f7e8d;font-weight:900}.s12-pct{font-size:25px;line-height:1;font-weight:950;color:#72dc66;letter-spacing:-.03em;margin-top:4px;white-space:nowrap}.s12-team{font-size:15px;font-weight:950;line-height:1.2}.s12-opp{color:#8d9aa8;font-weight:750}.s12-market{font-size:10px;color:#8c9aaa;margin-top:5px;font-weight:750}.s12-market strong{color:#e2e8ee;font-size:11px}.s12-tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.s12-tag{border:1px solid #233141;border-radius:999px;padding:4px 6px;font-size:8px;font-weight:850;color:#9aa8b6;background:#0a1017}.s12-tag.good{color:#7ade6f}.s12-tag.warn{color:#e3b96b}.s12-tag.bad{color:#e08b8b}.s12-action{min-width:58px;border:1px solid #2a3a4c;background:#141e29;color:#f4f7fb;border-radius:10px;padding:9px 10px;font-size:10px;font-weight:900;cursor:pointer}.s12-action.selected{color:#72dc66}.s12-action:disabled{opacity:.55;cursor:default}
  .s12-details{margin-top:12px;border-top:1px solid rgba(255,255,255,.06);padding-top:10px}.s12-details summary{cursor:pointer;font-size:10px;font-weight:900;color:#9aa8b6}.s12-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:9px}.s12-detail{background:#0a1017;border-radius:10px;padding:8px}.s12-detail-label{font-size:8px;color:#6f7e8d;text-transform:uppercase;font-weight:850}.s12-detail-value{font-size:11px;font-weight:900;margin-top:2px}.s12-history{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.s12-history-item{border:1px solid #243242;border-radius:999px;padding:5px 7px;font-size:9px;color:#9ba8b5}.s12-cal{margin-top:14px;border:1px solid #202d3c;background:#0c1219;border-radius:14px;padding:11px}.s12-cal summary{font-size:10px;font-weight:900;color:#98a7b6;cursor:pointer}.s12-cal-row{display:grid;grid-template-columns:1fr 44px 62px 62px;gap:6px;font-size:9px;padding:6px 0;border-bottom:1px solid rgba(255,255,255,.05)}.s12-cal-row:last-child{border:0}.s12-cal-h{color:#687788;font-weight:850}.s12-footer-note{font-size:9px;color:#687788;line-height:1.4;margin:10px 2px}
  @media(max-width:600px){.s12-body{padding:12px}.s12-command{grid-template-columns:repeat(2,minmax(0,1fr))}.s12-main{grid-template-columns:78px minmax(0,1fr);gap:11px}.s12-main>div:last-child{grid-column:2}.s12-action{margin-top:2px}.s12-strategy-grid{grid-template-columns:1fr}.s12-pct{font-size:23px}}
</style>
<script>
(function(){
  var overlay=null,data=null,selectedEntry=null,sortMode='pct-desc',dashboard=null;
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
  function code(name){var m={'Arizona Cardinals':'ARI','Atlanta Falcons':'ATL','Baltimore Ravens':'BAL','Buffalo Bills':'BUF','Carolina Panthers':'CAR','Chicago Bears':'CHI','Cincinnati Bengals':'CIN','Cleveland Browns':'CLE','Dallas Cowboys':'DAL','Denver Broncos':'DEN','Detroit Lions':'DET','Green Bay Packers':'GB','Houston Texans':'HOU','Indianapolis Colts':'IND','Jacksonville Jaguars':'JAX','Kansas City Chiefs':'KC','Las Vegas Raiders':'LV','Los Angeles Chargers':'LAC','Los Angeles Rams':'LAR','Miami Dolphins':'MIA','Minnesota Vikings':'MIN','New England Patriots':'NE','New Orleans Saints':'NO','New York Giants':'NYG','New York Jets':'NYJ','Philadelphia Eagles':'PHI','Pittsburgh Steelers':'PIT','San Francisco 49ers':'SF','Seattle Seahawks':'SEA','Tampa Bay Buccaneers':'TB','Tennessee Titans':'TEN','Washington Commanders':'WAS'};return m[name]||name}
  function ml(v){var n=Number(v);if(!Number.isFinite(n))return '—';return n>0?'+'+Math.round(n):String(Math.round(n))}
  function signed(v){var n=Number(v);if(!Number.isFinite(n))return '—';if(n===0)return 'PK';return n>0?'+'+n:String(n)}
  function pct(v){var n=Number(v);return Number.isFinite(n)?Math.round(n*10)/10:0}
  function api(path,options){var o=Object.assign({credentials:'same-origin',cache:'no-store'},options||{});return fetch(path,o).then(async function(r){var b=await r.json().catch(function(){return {error:'Invalid response'}});if(!r.ok)throw new Error(b.message||b.error||'Request failed');return b})}
  async function load(){dashboard=await api('/api/dashboard/nfl');data=await api('/api/survivor/analytics?season='+encodeURIComponent(dashboard.season)+'&week='+encodeURIComponent(dashboard.week))}
  function entry(){return selectedEntry?data.entries.find(function(e){return e.id===selectedEntry}):null}
  function strategy(){return selectedEntry?data.entryStrategies.find(function(s){return s.entryId===selectedEntry}):null}
  function commandCenter(){return '<div class="s12-command">'+data.entries.map(function(e){var p=e.currentPick;return '<button class="s12-entry-card" data-s12-entry="'+e.id+'" style="text-align:left;color:inherit;cursor:pointer"><div class="s12-entry-name">'+esc(e.name)+'</div><div class="s12-entry-pick">'+(p?esc(code(p.team)):'No pick')+'</div><div class="s12-entry-meta">Top '+esc(pct(e.remainingStrength.topProbability))+'% · '+esc(e.availableCount)+' available</div></button>'}).join('')+'</div>'}
  function entryChips(){return '<div class="s12-entries"><button class="s12-entry '+(!selectedEntry?'active':'')+'" data-s12-entry="">All teams</button>'+data.entries.map(function(e){return '<button class="s12-entry '+(e.id===selectedEntry?'active':'')+'" data-s12-entry="'+e.id+'">'+esc(e.name)+'</button>'}).join('')+'</div>'}
  function strategyPanel(){var s=strategy();if(!s)return '<div class="s12-strategy"><div class="s12-strategy-title">Six-entry view</div><div class="s12-strategy-meta">Choose a Muzzle entry to compare pure safety, alternative strength, remaining teams, and strategic value.</div></div>';var safe=s.safest,best=s.bestStrategicValue;return '<div class="s12-strategy"><div class="s12-strategy-title">Decision support · '+esc(entry().name)+'</div><div class="s12-strategy-grid"><div><div class="s12-strategy-label">PURE SAFETY</div><div class="s12-strategy-team">'+esc(code(safe&&safe.team))+' · '+esc(pct(safe&&safe.winProbability))+'%</div><div class="s12-strategy-meta">Next alternative: '+esc(code(s.alternativeTeam))+' '+esc(pct(s.alternativeProbability))+'% · drop-off '+esc(s.alternativeDrop==null?'—':s.alternativeDrop+' pts')+'</div></div><div><div class="s12-strategy-label">STRATEGIC VALUE</div><div class="s12-strategy-team">'+esc(code(best&&best.team))+' · '+esc(pct(best&&best.winProbability))+'%</div><div class="s12-strategy-meta">Safety difference '+esc(best&&best.safetyDifference!=null?best.safetyDifference+' pts':'—')+'</div><div class="s12-reason">'+esc((best&&best.reasons||[]).join(' · ')||'No strong reason to deviate from pure safety.')+'</div></div></div></div>'}
  function filtered(){var e=entry(),list=(data.board||[]).map(function(c){var used=e?e.priorUsedTeams.includes(c.team):false;return Object.assign({},c,{entryUsed:used,entryAvailable:!used})});if(sortMode==='pct-asc')list.sort(function(a,b){return pct(a.winProbability)-pct(b.winProbability)});else if(sortMode==='ml')list.sort(function(a,b){return (Number(a.moneyline)||99999)-(Number(b.moneyline)||99999)});else if(sortMode==='spread')list.sort(function(a,b){return (Number(a.spread)||99999)-(Number(b.spread)||99999)});else if(sortMode==='available')list.sort(function(a,b){return b.availableEntries-a.availableEntries||pct(b.winProbability)-pct(a.winProbability)});else if(sortMode==='exposure')list.sort(function(a,b){return a.exposure-b.exposure||pct(b.winProbability)-pct(a.winProbability)});else list.sort(function(a,b){return pct(b.winProbability)-pct(a.winProbability)});return list}
  function tag(text,cls){return '<span class="s12-tag '+(cls||'')+'">'+esc(text)+'</span>'}
  function card(c,i){var e=entry(),current=e&&e.currentPick&&e.currentPick.team===c.team,used=c.entryUsed;var movement=c.movement&&c.movement.change,moveText=movement==null?'Movement —':(movement>0?'↑ ':'')+(movement<0?'↓ ':'')+Math.abs(movement)+' pts';var moveClass=movement>0?'good':movement<0?'warn':'';var fv=c.futureValue||{},futureText=fv.dataAvailable?(fv.bestFutureProbability+'% W'+fv.bestFutureWeek+' vs '+code(fv.bestFutureOpponent)):'Future —';var action='';if(e){action=current?'<button class="s12-action selected" disabled>Selected</button>':used?'<button class="s12-action" disabled>Used</button>':'<button class="s12-action" data-s12-pick="'+esc(c.team)+'" data-game="'+esc(c.gameId)+'">Use</button>'}return '<div class="s12-card '+(used?'used ':'')+(current?'selected':'')+'"><div class="s12-main"><div><div class="s12-rank">#'+(i+1)+'</div><div class="s12-pct">'+esc(pct(c.winProbability))+'%</div></div><div><div class="s12-team">'+esc(code(c.team))+' <span class="s12-opp">vs '+esc(code(c.opponent))+'</span></div><div class="s12-market">ML <strong>'+esc(ml(c.moneyline))+'</strong> · Spread <strong>'+esc(signed(c.spread))+'</strong></div><div class="s12-tags">'+tag('Available '+c.availableEntries+'/'+c.totalEntries,c.availableEntries===c.totalEntries?'good':'')+tag('Selected '+c.exposure+'/'+c.totalEntries,c.exposure>=3?'warn':'')+tag('Agreement '+c.marketAgreement.label,c.marketAgreement.label==='Strong'?'good':c.marketAgreement.label==='Mixed'?'warn':'')+tag(moveText,moveClass)+tag(futureText,fv.bestFutureProbability>c.winProbability+4?'warn':'')+'</div></div><div>'+action+'</div></div><details class="s12-details"><summary>Analytics</summary><div class="s12-detail-grid"><div class="s12-detail"><div class="s12-detail-label">Market agreement</div><div class="s12-detail-value">'+esc(c.marketAgreement.label)+' · range '+esc(c.marketAgreement.spread==null?'—':c.marketAgreement.spread+' pts')+'</div></div><div class="s12-detail"><div class="s12-detail-label">Probability movement</div><div class="s12-detail-value">'+esc(c.movement.firstProbability==null?'—':c.movement.firstProbability+'% → '+c.movement.currentProbability+'%')+'</div></div><div class="s12-detail"><div class="s12-detail-label">Future value</div><div class="s12-detail-value">'+esc(futureText)+'</div></div><div class="s12-detail"><div class="s12-detail-label">Schedule scarcity</div><div class="s12-detail-value">'+esc(fv.scarcity||'Unavailable')+' · '+esc(fv.strongFutureSpots||0)+' strong spots</div></div></div></details></div>'}
  function history(){var e=entry();if(!e)return '';return '<details class="s12-cal" open><summary>'+esc(e.name)+' pick history</summary><div class="s12-history">'+(e.history.length?e.history.map(function(h){return '<span class="s12-history-item">W'+h.week+' '+esc(code(h.team))+' · '+esc(h.outcome)+'</span>'}).join(''):'<span class="s12-history-item">No picks recorded yet</span>')+'</div></details>'}
  function calibration(){return '<details class="s12-cal"><summary>Historical probability calibration</summary><div class="s12-footer-note">Compares stored market favorite probabilities with actual completed-game outcomes. Small samples should be treated cautiously.</div>'+(data.calibration.length?'<div class="s12-cal-row s12-cal-h"><span>Bucket</span><span>N</span><span>Pred.</span><span>Actual</span></div>'+data.calibration.map(function(r){return '<div class="s12-cal-row"><span>'+esc(r.bucket)+'</span><span>'+r.count+'</span><span>'+r.predictedRate+'%</span><span>'+r.actualWinRate+'%</span></div>'}).join(''):'<div class="s12-footer-note">No completed games with stored moneylines yet.</div>')+'</details>'}
  function render(){if(!overlay||!data)return;var e=entry(),list=filtered();overlay.innerHTML='<div class="s12-head"><button class="s12-back" data-s12-close>‹</button><div><div class="s12-title">SURVIVOR · WEEK '+esc(data.week)+'</div><div class="s12-sub">Win probability first · six-entry strategy analytics</div></div></div><div class="s12-body">'+entryChips()+commandCenter()+strategyPanel()+'<div class="s12-toolbar"><div class="s12-count">'+list.length+' teams · '+(e?esc(e.name):'all entries')+'</div><select class="s12-sort" data-s12-sort><option value="pct-desc" '+(sortMode==='pct-desc'?'selected':'')+'>Win % · High to Low</option><option value="pct-asc" '+(sortMode==='pct-asc'?'selected':'')+'>Win % · Low to High</option><option value="ml" '+(sortMode==='ml'?'selected':'')+'>Moneyline · Favorite First</option><option value="spread" '+(sortMode==='spread'?'selected':'')+'>Spread · Favorite First</option><option value="available" '+(sortMode==='available'?'selected':'')+'>Available · Most Entries</option><option value="exposure" '+(sortMode==='exposure'?'selected':'')+'>Exposure · Lowest First</option></select></div><div class="s12-note">Win probability is never replaced by a composite score. Future value, scarcity, market agreement, movement, alternative strength, and six-entry exposure are shown separately so you can see why a strategic choice may differ from the safest team.</div>'+list.map(card).join('')+history()+calibration()+'<div class="s12-footer-note">'+esc(data.futureData.note)+'</div></div>';bind()}
  function bind(){overlay.querySelector('[data-s12-close]').onclick=close;overlay.querySelectorAll('[data-s12-entry]').forEach(function(b){b.onclick=function(){var v=b.getAttribute('data-s12-entry');selectedEntry=v?Number(v):null;render()}});var sort=overlay.querySelector('[data-s12-sort]');sort.onchange=function(){sortMode=sort.value;render()};overlay.querySelectorAll('[data-s12-pick]').forEach(function(b){b.onclick=async function(){var e=entry(),team=b.getAttribute('data-s12-pick');if(!e)return;if(!confirm('Use '+code(team)+' for '+e.name+' in Week '+data.week+'?'))return;try{await api('/api/survivor/picks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entryId:e.id,season:data.season,week:data.week,team:team,gameId:b.getAttribute('data-game')})});data=null;overlay.innerHTML='<div class="s12-head"><button class="s12-back" data-s12-close>‹</button><div><div class="s12-title">SURVIVOR</div><div class="s12-sub">Refreshing after pick…</div></div></div><div class="s12-body"><div class="s12-loading">Updating six-entry analytics…</div></div>';overlay.querySelector('[data-s12-close]').onclick=close;await load();render()}catch(err){alert(err.message+' — unlock Admin Tools with your PIN first.')}}})}
  async function open(){if(overlay)return;document.querySelectorAll('.survivor-overlay').forEach(function(x){x.remove()});overlay=document.createElement('div');overlay.className='s12-overlay';overlay.innerHTML='<div class="s12-head"><button class="s12-back" data-s12-close>‹</button><div><div class="s12-title">SURVIVOR</div><div class="s12-sub">Loading analytics once…</div></div></div><div class="s12-body"><div class="s12-loading">Loading all six entries and the weekly market board…</div></div>';document.body.appendChild(overlay);overlay.querySelector('[data-s12-close]').onclick=close;try{await load();render()}catch(err){overlay.querySelector('.s12-body').innerHTML='<div class="s12-error">'+esc(err.message)+'</div>'}}
  function close(){if(overlay){overlay.remove();overlay=null}}
  document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('[data-survivor-nav]');if(!b)return;ev.preventDefault();ev.stopImmediatePropagation();open()},true);
})();
</script>`;
  return html.replace("</body>", extension + "\n</body>");
}
