export const APP_VERSION = '0.22.0';

export function canonicalAppPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#080b10">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png">
<title>NFL Spread Tool</title>
<style>
:root{--bg:#080b10;--panel:#0e141c;--panel2:#111a23;--border:#233041;--text:#f4f7fb;--muted:#8c9aaa;--blue:#4ca6ff;--green:#72dc66;--yellow:#e1c45b;--red:#ef8e8e}
*{box-sizing:border-box}html{background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}body{margin:0;background:var(--bg)}button,input,select{font:inherit}.app{max-width:560px;margin:0 auto;min-height:100vh;padding-bottom:82px}.topbar{padding:calc(17px + env(safe-area-inset-top)) 14px 11px;display:flex;align-items:center;justify-content:space-between;gap:10px;border-bottom:1px solid rgba(255,255,255,.07);position:sticky;top:0;z-index:10;background:rgba(8,11,16,.96);backdrop-filter:blur(16px)}.brand{font-size:13px;font-weight:950;letter-spacing:.055em}.brand-sub{font-size:9px;color:var(--muted);margin-top:3px;font-weight:700}.week-pill{font-size:9px;font-weight:900;padding:7px 9px;border:1px solid var(--border);border-radius:999px;white-space:nowrap}.content{padding:11px 12px 22px}.status{border:1px solid rgba(114,220,102,.22);background:#0d151b;border-radius:11px;padding:9px 10px;margin-bottom:11px}.status-top{display:flex;justify-content:space-between;gap:8px;font-size:9px;font-weight:900}.status-state{color:var(--green)}.status-sub{font-size:8px;color:var(--muted);margin-top:4px}.section{margin-bottom:15px}.section-head{display:flex;align-items:end;justify-content:space-between;margin:0 2px 8px}.section-title{font-size:10px;font-weight:950;letter-spacing:.065em;text-transform:uppercase}.section-meta{font-size:9px;color:var(--muted)}.empty,.notice{border:1px dashed var(--border);border-radius:13px;padding:18px;color:var(--muted);font-size:11px;line-height:1.5}.error{color:var(--red)}
.pulse{border:1px solid var(--border);background:var(--panel);border-radius:15px;padding:11px}.pulse-row{display:grid;grid-template-columns:92px repeat(3,1fr);gap:5px;align-items:center;padding:5px 0}.pulse-row+.pulse-row{border-top:1px solid rgba(255,255,255,.05)}.pulse-label{font-size:10px;font-weight:900}.pulse-cell{border:1px solid rgba(255,255,255,.06);background:#0a1017;border-radius:8px;padding:6px 3px;text-align:center;color:var(--muted)}.pulse-cell strong{display:block;color:var(--text);font-size:11px}.pulse-cell span{font-size:7px}.pulse-cell.hot{border-color:rgba(114,220,102,.32);background:rgba(114,220,102,.07)}.pulse-cell.hot strong{color:var(--green)}.pulse-head{font-size:7px;color:var(--muted);text-align:center;text-transform:uppercase}
.focus-list{display:grid;gap:7px}.focus-row,.game-card{width:100%;text-align:left;color:var(--text);border:1px solid var(--border);background:var(--panel);border-radius:14px;cursor:pointer}.focus-row{display:grid;grid-template-columns:34px 1fr auto;gap:9px;align-items:center;padding:10px}.grade{width:30px;height:30px;border-radius:9px;display:grid;place-items:center;background:rgba(76,166,255,.13);color:var(--blue);font-size:13px;font-weight:950}.focus-match{font-size:12px;font-weight:950}.focus-detail{font-size:9px;color:var(--muted);margin-top:3px}.focus-rate{font-size:15px;font-weight:950;color:var(--green)}
.filters{display:flex;gap:6px;overflow:auto;margin-bottom:9px}.filter{border:1px solid var(--border);background:var(--panel);color:var(--muted);border-radius:999px;padding:7px 10px;font-size:9px;font-weight:850;white-space:nowrap}.filter.active{background:var(--blue);border-color:var(--blue);color:#06111b}.games{display:grid;gap:9px}.game-card{padding:12px}.game-top{display:grid;grid-template-columns:1fr 58px 1fr;align-items:start}.team{display:flex;gap:8px;align-items:center}.team.home{justify-content:flex-end;text-align:right}.logo{width:34px;height:34px;object-fit:contain}.team-code{font-size:14px;font-weight:950}.team-name{font-size:8px;color:var(--muted);margin-top:1px}.game-state{text-align:center;font-size:8px;font-weight:950;color:var(--muted);padding-top:6px;letter-spacing:.07em}.game-state.live{color:var(--green)}.score{font-size:27px;font-weight:950;margin-top:5px}.score.loser{color:#98a5b3}.kickoff{font-size:9px;color:var(--muted);text-align:center;margin:9px 0}.metrics{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}.metric{background:var(--panel2);border-radius:8px;padding:7px}.metric-label{font-size:7px;color:var(--muted);text-transform:uppercase}.metric-value{font-size:10px;font-weight:900;margin-top:3px}.primary{color:var(--blue)}.signal{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:8px;padding:8px;border:1px solid rgba(76,166,255,.22);background:rgba(76,166,255,.06);border-radius:9px}.signal-label{font-size:7px;color:var(--muted);font-weight:900}.signal-value{font-size:11px;font-weight:950}.signal-meta{font-size:8px;color:var(--muted);white-space:nowrap}
.pick-summary{border:1px solid var(--border);background:var(--panel);border-radius:13px;padding:11px;display:flex;justify-content:space-between;align-items:center}.pick-summary strong{font-size:12px}.pick-summary span{font-size:9px;color:var(--muted)}.link-btn{border:0;background:transparent;color:var(--blue);font-size:10px;font-weight:900}
.week-nav{display:grid;grid-template-columns:44px 1fr 44px;gap:8px;align-items:center;margin-bottom:10px}.week-nav button{border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:10px;height:36px}.week-nav strong{text-align:center;font-size:12px}.pick-game{border:1px solid var(--border);background:var(--panel);border-radius:14px;padding:11px;margin-bottom:8px}.pick-match{font-size:9px;color:var(--muted);text-align:center;margin-bottom:7px}.pick-options{display:grid;grid-template-columns:1fr 1fr;gap:7px}.pick-team{border:1px solid var(--border);background:#0a1017;color:var(--text);border-radius:11px;padding:10px;text-align:left}.pick-team.selected{border-color:var(--blue);background:rgba(76,166,255,.1)}.pick-team.winner{border-color:var(--green)}.pick-team.wrong{border-color:var(--red)}.pick-team strong{display:block;font-size:12px}.pick-team span{font-size:8px;color:var(--muted)}.pick-result{font-size:8px;font-weight:900;text-align:center;margin-top:8px}.pick-result.correct{color:var(--green)}.pick-result.wrong{color:var(--red)}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.action{border:1px solid var(--border);background:var(--panel2);color:var(--text);border-radius:11px;padding:10px;font-size:9px;font-weight:900}.action.primary{background:var(--blue);color:#06111b;border-color:var(--blue)}.copy-preview{white-space:pre-wrap;border:1px solid var(--border);background:#090e14;color:#bdc8d2;border-radius:11px;padding:10px;margin-top:8px;font:10px/1.5 ui-monospace,monospace}
.tools-intro{border:1px solid rgba(76,166,255,.28);background:rgba(76,166,255,.07);border-radius:14px;padding:13px;margin-bottom:11px}.tools-intro strong{font-size:12px}.tools-intro p{font-size:9px;color:var(--muted);line-height:1.45;margin:5px 0 0}.admin-row{display:flex;gap:7px}.admin-row input{min-width:0;flex:1;border:1px solid var(--border);background:#090e14;color:var(--text);border-radius:10px;padding:10px}.tool-list{display:grid;gap:7px}.tool{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:12px;padding:11px;text-align:left}.tool strong{display:block;font-size:10px}.tool span{display:block;font-size:8px;color:var(--muted);margin-top:3px}.tool.secondary{opacity:.82}.tool-output{white-space:pre-wrap;max-height:260px;overflow:auto;border:1px solid var(--border);background:#090e14;color:#bdc8d2;border-radius:11px;padding:10px;font:9px/1.45 ui-monospace,monospace}
.detail-head{display:grid;grid-template-columns:38px 1fr 38px;align-items:center;padding:calc(12px + env(safe-area-inset-top)) 9px 11px;border-bottom:1px solid rgba(255,255,255,.07);position:sticky;top:0;background:rgba(8,11,16,.96);z-index:12}.back{border:0;background:transparent;color:var(--text);font-size:28px}.detail-title{text-align:center;font-size:13px;font-weight:950}.hero{text-align:center;padding:16px 12px 8px}.hero-score{font-size:31px;font-weight:950}.hero-state{font-size:9px;color:var(--green);font-weight:900;margin-bottom:4px}.detail-card{border:1px solid var(--border);background:var(--panel);border-radius:14px;padding:12px;margin-bottom:9px}.detail-card h3{font-size:9px;letter-spacing:.06em;text-transform:uppercase;margin:0 0 9px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.detail-box{background:var(--panel2);border-radius:9px;padding:8px}.detail-box span{display:block;color:var(--muted);font-size:7px;text-transform:uppercase}.detail-box strong{font-size:10px}.books summary{cursor:pointer;font-size:9px;font-weight:900}.books table{width:100%;font-size:9px;margin-top:9px;border-collapse:collapse}.books td{padding:6px;border-top:1px solid rgba(255,255,255,.05)}
.bottom-nav{position:fixed;left:50%;bottom:0;transform:translateX(-50%);width:100%;max-width:560px;z-index:30;display:grid;grid-template-columns:repeat(4,1fr);padding:7px 7px calc(7px + env(safe-area-inset-bottom));background:rgba(7,10,14,.96);border-top:1px solid rgba(255,255,255,.08);backdrop-filter:blur(18px)}.nav{border:0;background:transparent;color:#718091;padding:6px 3px}.nav.active{color:var(--blue)}.nav-icon{display:block;font-size:18px}.nav-label{display:block;font-size:9px;font-weight:850;margin-top:3px}.loading{padding:80px 20px;text-align:center;color:var(--muted)}
</style>
</head>
<body><div id="app" class="app"><div class="loading">Loading the week…</div></div>
<script>
(function(){
'use strict';
var VERSION='0.22.0';
var S={tab:'dashboard',dashboard:null,focus:null,pool:null,fresh:null,selected:null,filter:'ALL',season:null,week:null,picksWeek:null,loading:true,error:null};
var TEAM={'Arizona Cardinals':'ARI','Atlanta Falcons':'ATL','Baltimore Ravens':'BAL','Buffalo Bills':'BUF','Carolina Panthers':'CAR','Chicago Bears':'CHI','Cincinnati Bengals':'CIN','Cleveland Browns':'CLE','Dallas Cowboys':'DAL','Denver Broncos':'DEN','Detroit Lions':'DET','Green Bay Packers':'GB','Houston Texans':'HOU','Indianapolis Colts':'IND','Jacksonville Jaguars':'JAX','Kansas City Chiefs':'KC','Las Vegas Raiders':'LV','Los Angeles Chargers':'LAC','Los Angeles Rams':'LAR','Miami Dolphins':'MIA','Minnesota Vikings':'MIN','New England Patriots':'NE','New Orleans Saints':'NO','New York Giants':'NYG','New York Jets':'NYJ','Philadelphia Eagles':'PHI','Pittsburgh Steelers':'PIT','San Francisco 49ers':'SF','Seattle Seahawks':'SEA','Tampa Bay Buccaneers':'TB','Tennessee Titans':'TEN','Washington Commanders':'WAS'};
function e(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function code(n){return TEAM[n]||String(n||'NFL').split(/\s+/).map(function(x){return x[0]}).join('').slice(0,3).toUpperCase()}
function logo(n){var slug=code(n).toLowerCase();if(slug==='was')slug='wsh';return 'https://a.espncdn.com/i/teamlogos/nfl/500/'+slug+'.png'}
function signed(v){var n=Number(v);return Number.isFinite(n)?(n===0?'PK':(n>0?'+':'')+n):'—'}
function pct(v){var n=Number(v);if(!Number.isFinite(n))return '—';return (n<=1?Math.round(n*1000)/10:Math.round(n*10)/10)+'%'}
function ml(v){var n=Number(v);return Number.isFinite(n)?(n>0?'+':'')+Math.round(n):'—'}
function tier(t){return t==='LE_3'||t==='<=3'?'0.5–3':t==='LE_7'||t==='<=7'?'3.5–7':t==='GT_7'||t==='>7'?'7.5+':t==='PICK_EM'?'PK':t||'—'}
function cls(v){return String(v||'').replace('AwayFavorite','Away Fav').replace('HomeFavorite','Home Fav').replace('AwayUnderdog','Away Dog').replace('HomeUnderdog','Home Dog')||'—'}
function kickoff(v){if(!v)return 'Kickoff unavailable';var d=new Date(v);return d.toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function gameState(g){if(g.final)return 'FINAL';if(g.live)return 'LIVE';return 'UPCOMING'}
function favorite(g){var a=Number(g.medianAwaySpread);if(!Number.isFinite(a))return 'No line';return (a<=0?code(g.awayTeam):code(g.homeTeam))+' '+signed(a<=0?a:-a)}
function json(path,opt){return fetch(path,Object.assign({cache:'no-store',credentials:'same-origin',headers:{accept:'application/json'}},opt||{})).then(function(r){return r.json().catch(function(){return {error:'Invalid response'}}).then(function(b){if(!r.ok)throw new Error(b.message||b.error||'Request failed');return b})})}
function header(){return '<header class="topbar"><div><div class="brand">NFL SPREAD TOOL</div><div class="brand-sub">Current-season engine · live market board</div></div><div class="week-pill">'+e(S.season||'—')+' · WEEK '+e(S.tab==='picks'?(S.picksWeek||S.week):S.week||'—')+'</div></header>'}
function nav(){return '<nav class="bottom-nav">'+[['dashboard','⌂','Dashboard'],['games','▦','Games'],['picks','✓','Picks'],['tools','⚙','Tools']].map(function(x){return '<button class="nav '+(S.tab===x[0]?'active':'')+'" data-tab="'+x[0]+'"><span class="nav-icon">'+x[1]+'</span><span class="nav-label">'+x[2]+'</span></button>'}).join('')+'</nav>'}
function status(){var f=S.fresh||{},state=f.overallState||f.state||'CURRENT';return '<div class="status"><div class="status-top"><span>DATA STATUS</span><span class="status-state">'+e(state)+'</span></div><div class="status-sub">'+e((S.dashboard&&S.dashboard.results?S.dashboard.results.completedGames+' completed · '+S.dashboard.results.awaitingCompletion+' awaiting completion':'Live market and score status'))+'</div></div>'}
function bucket(name,t){var b=S.dashboard&&S.dashboard.liveWeekStats&&S.dashboard.liveWeekStats.buckets&&S.dashboard.liveWeekStats.buckets[name+'|'+t];if(!b)return null;var w=Number(b.wins||0),l=Number(b.losses||0),p=Number(b.pushes||0),n=w+l;return {rate:b.coverRate==null?(n?Math.round(w/n*1000)/10:null):b.coverRate,record:w+'-'+l+(p?'-'+p:'')}}
function pulse(){var rows=[['Away Dog','AwayDog'],['Away Fav','AwayFav'],['Home Dog','HomeDog'],['Home Fav','HomeFav']],ts=[['0.5–3','<=3'],['3.5–7','<=7'],['7.5+','>7']];return '<section class="section"><div class="section-head"><div class="section-title">Tier Pulse</div><div class="section-meta">Current season</div></div><div class="pulse"><div class="pulse-row"><div></div>'+ts.map(function(t){return '<div class="pulse-head">'+t[0]+'</div>'}).join('')+'</div>'+rows.map(function(r){return '<div class="pulse-row"><div class="pulse-label">'+r[0]+'</div>'+ts.map(function(t){var b=bucket(r[1],t[1]);var hot=b&&Number(b.rate)>=57;return '<div class="pulse-cell '+(hot?'hot':'')+'"><strong>'+(b&&b.rate!=null?e(b.rate)+'%':'—')+'</strong><span>'+(b?e(b.record):'n=0')+'</span></div>'}).join('')+'</div>'}).join('')+'</div></section>'}
function focus(){var list=(S.focus&&S.focus.games)||[];list=list.filter(function(g){return g.focus||g.grade==='A'||g.grade==='B'||g.grade==='C'}).slice(0,4);return '<section class="section"><div class="section-head"><div class="section-title">Top Opportunities</div><div class="section-meta">'+list.length+' games</div></div>'+(list.length?'<div class="focus-list">'+list.map(function(g){var s=g.spread||g;return '<button class="focus-row" data-game="'+e(g.gameId||g.id)+'"><span class="grade">'+e(s.grade||g.grade||'—')+'</span><span><div class="focus-match">'+e(code(g.awayTeam))+' @ '+e(code(g.homeTeam))+'</div><div class="focus-detail">'+e(s.projectedTeam?code(s.projectedTeam)+' · '+tier(g.classification&&g.classification.tier||s.tier):'Current-week signal')+' · n='+e(s.sampleSize||g.sampleSize||0)+'</div></span><span class="focus-rate">'+e(s.coverRate||g.projectedCoverRate||'—')+'%</span></button>'}).join('')+'</div>':'<div class="empty">No Focus opportunities yet. The current-season sample is still building.</div>')+'</section>'}
function pickSummary(){var p=S.pool||{},games=p.games||[],picked=games.filter(function(g){return g.pick}).length;return '<section class="section"><div class="section-head"><div class="section-title">Your Picks</div><div class="section-meta">Week '+e(S.week)+'</div></div><div class="pick-summary"><div><strong>'+picked+' of '+games.length+' selected</strong><br><span>'+e(p.summary&&p.summary.correct||0)+' correct · '+e(p.summary&&p.summary.wrong||0)+' wrong</span></div><button class="link-btn" data-tab="picks">Open Picks ›</button></div></section>'}
function filters(){var games=S.dashboard&&S.dashboard.games||[];return '<div class="filters">'+['ALL','A','B','C'].map(function(f){var count=f==='ALL'?games.length:games.filter(function(g){return g.grade===f}).length;return '<button class="filter '+(S.filter===f?'active':'')+'" data-filter="'+f+'">'+f+' '+count+'</button>'}).join('')+'</div>'}
function gameCard(g){var st=gameState(g),a=g.final?g.final.awayScore:g.live&&g.live.awayScore,h=g.final?g.final.homeScore:g.live&&g.live.homeScore,post=g.postgame,b=post&&post.liveBucket;var signal=st==='FINAL'?(post?(post.spreadResult==='PUSH'?'PUSH':code(post.coveringTeam)+' COVERED'):'FINAL'):(g.projectedTeam?code(g.projectedTeam)+' · '+pct(g.projectedCoverRate):'No tier edge yet');var meta=st==='FINAL'?(b?(b.wins||0)+'-'+(b.losses||0)+' · '+pct(b.coverRate):'Final stats unavailable'):'n='+(g.sampleSize||0)+(g.grade?' · '+g.grade:'');return '<button class="game-card" data-game="'+e(g.id)+'"><div class="game-top"><div class="team"><img class="logo" alt="" src="'+e(logo(g.awayTeam))+'"><div><div class="team-code">'+e(code(g.awayTeam))+'</div><div class="team-name">'+e(g.awayTeam)+'</div>'+(a!=null?'<div class="score '+(Number(a)<Number(h)?'loser':'')+'">'+e(a)+'</div>':'')+'</div></div><div class="game-state '+(st==='LIVE'?'live':'')+'">'+st+'</div><div class="team home"><div><div class="team-code">'+e(code(g.homeTeam))+'</div><div class="team-name">'+e(g.homeTeam)+'</div>'+(h!=null?'<div class="score '+(Number(h)<Number(a)?'loser':'')+'">'+e(h)+'</div>':'')+'</div><img class="logo" alt="" src="'+e(logo(g.homeTeam))+'"></div></div>'+(st==='UPCOMING'?'<div class="kickoff">'+e(kickoff(g.kickoffAt))+'</div>':'')+'<div class="metrics"><div class="metric"><div class="metric-label">Consensus</div><div class="metric-value primary">'+e(favorite(g))+'</div></div><div class="metric"><div class="metric-label">Tier</div><div class="metric-value">'+e(tier(g.classification&&g.classification.tier))+'</div></div><div class="metric"><div class="metric-label">Class</div><div class="metric-value">'+e(cls(g.classification&&g.classification.away))+'</div></div></div><div class="signal"><span class="signal-label">'+(st==='FINAL'?'FINAL SPREAD RESULT':'TIER EDGE')+'</span><strong class="signal-value">'+e(signal)+'</strong><span class="signal-meta">'+e(meta)+'</span></div></button>'}
function gamesSection(limit){var games=S.dashboard&&S.dashboard.games||[];if(S.filter!=='ALL')games=games.filter(function(g){return g.grade===S.filter});if(limit)games=games.slice(0,limit);return '<section class="section"><div class="section-head"><div class="section-title">'+(limit?'Next Games':'All Games')+'</div><div class="section-meta">Week '+e(S.week)+'</div></div>'+(!limit?filters():'')+'<div class="games">'+games.map(gameCard).join('')+'</div></section>'}
function dashboard(){return header()+'<main class="content">'+status()+pulse()+focus()+pickSummary()+'</main>'+nav()}
function games(){return header()+'<main class="content">'+status()+gamesSection()+'</main>'+nav()}
function poolText(compact){var p=S.pool||{},lines=['Week '+(S.picksWeek||S.week)+' Picks'];(p.games||[]).filter(function(g){return g.pick}).forEach(function(g){var away=g.pick===g.awayTeam,m=away?g.market.awayMoneyline:g.market.homeMoneyline,w=away?g.market.awayWinPct:g.market.homeWinPct;lines.push(compact?code(g.pick)+' ('+ml(m)+', '+pct(w)+')':code(g.pick)+' — ML '+ml(m)+' · '+pct(w)+' market win')});return compact?lines[0]+':\n'+lines.slice(1).join(', '):lines.join('\n')}
function pickGame(g){function option(team,isAway){var selected=g.pick===team,result=selected&&g.pickResult;var m=isAway?g.market.awayMoneyline:g.market.homeMoneyline,w=isAway?g.market.awayWinPct:g.market.homeWinPct;return '<button class="pick-team '+(selected?'selected ':'')+(result==='CORRECT'?'winner':result==='WRONG'?'wrong':'')+'" data-pick-game="'+e(g.gameId)+'" data-team="'+e(team)+'"><strong>'+e(code(team))+'</strong><span>ML '+e(ml(m))+' · '+e(pct(w))+' market</span></button>'}return '<div class="pick-game"><div class="pick-match">'+e(kickoff(g.kickoffAt))+'</div><div class="pick-options">'+option(g.awayTeam,true)+option(g.homeTeam,false)+'</div>'+(g.pickResult?'<div class="pick-result '+e(String(g.pickResult).toLowerCase())+'">'+e(g.pickResult)+'</div>':'')+'</div>'}
function picks(){var p=S.pool||{},games=p.games||[],done=games.length&&games.every(function(g){return g.final});var selected=games.filter(function(g){return g.pick}).length;return header()+'<main class="content"><div class="week-nav"><button data-week="-1">‹</button><strong>WEEK '+e(S.picksWeek||S.week)+(done?' · FINAL':'')+'</strong><button data-week="1">›</button></div><section class="section"><div class="section-head"><div class="section-title">'+(done?'Results':'Weekly Picks')+'</div><div class="section-meta">'+selected+'/'+games.length+' selected</div></div>'+games.map(pickGame).join('')+'<div class="actions"><button class="action primary" data-copy="detail">Copy Detailed</button><button class="action" data-copy="compact">Copy Compact</button></div><div class="copy-preview" data-preview>'+e(poolText(false))+'</div></section></main>'+nav()}
function tools(){return header()+'<main class="content">'+status()+'<div class="tools-intro"><strong>Tools & Admin</strong><p>Routine checks are automatic. Manual controls are available for recovery and verification.</p></div><section class="section"><div class="section-head"><div class="section-title">Admin Session</div><div class="section-meta" data-auth-state>Checking…</div></div><div class="admin-row"><input type="password" data-pin placeholder="Enter PIN"><button class="action primary" data-unlock>Unlock</button></div></section><section class="section"><div class="section-head"><div class="section-title">Manual Actions</div></div><div class="tool-list">'+tool('refresh','Refresh Game Data','Scores first, then current spreads and moneylines',false)+tool('integrity','Results Integrity','Verify completed games and missing finals',false)+tool('usage','API Usage','Review provider calls and remaining credits',false)+tool('context','Update Context','Refresh weather, rest and schedule context',true)+tool('history','Load Historical Data','Import the historical reference dataset',true)+tool('cache','Build History Cache','Rebuild stored weekly summaries',true)+'</div></section><section class="section"><div class="section-head"><div class="section-title">Output</div><div class="section-meta">v'+VERSION+'</div></div><div class="tool-output" data-output>Ready.</div></section></main>'+nav()}
function tool(action,name,desc,secondary){return '<button class="tool '+(secondary?'secondary':'')+'" data-action="'+action+'"><span><strong>'+name+'</strong><span>'+desc+'</span></span><b>›</b></button>'}
function detail(){var g=(S.dashboard&&S.dashboard.games||[]).find(function(x){return x.id===S.selected});if(!g)return games();var st=gameState(g),post=g.postgame,books=(g.books||[]);return '<div><header class="detail-head"><button class="back" data-back>‹</button><div class="detail-title">'+e(code(g.awayTeam))+' @ '+e(code(g.homeTeam))+'</div><div></div></header><div class="hero"><div class="hero-state">'+st+'</div><div class="hero-score">'+(g.final?e(g.final.awayScore)+'–'+e(g.final.homeScore):e(favorite(g)))+'</div><div class="kickoff">'+e(kickoff(g.kickoffAt))+'</div></div><main class="content">'+(st==='FINAL'?'<section class="detail-card"><h3>Spread Result</h3><div class="signal-value">'+e(post?(post.spreadResult==='PUSH'?'PUSH':code(post.coveringTeam)+' COVERED'):'Final result')+'</div></section>':'')+'<section class="detail-card"><h3>'+(st==='FINAL'?'Original Thesis':'Current Outlook')+'</h3><div class="detail-grid"><div class="detail-box"><span>Our thesis</span><strong>'+e(g.projectedTeam?code(g.projectedTeam)+' '+signed(g.projectedSpread||g.medianAwaySpread):'No edge')+'</strong></div><div class="detail-box"><span>Current spread</span><strong>'+e(favorite(g))+'</strong></div><div class="detail-box"><span>Tier</span><strong>'+e(tier(g.classification&&g.classification.tier))+'</strong></div><div class="detail-box"><span>Sample</span><strong>n='+e(g.sampleSize||0)+' · '+e(g.grade||'—')+'</strong></div></div></section><section class="detail-card"><h3>Why We Cared</h3><div class="notice">'+e(g.projectionStatus==='READY'?'Current-season tier and market context created the signal.':'No standout current-season signal was assigned.')+'</div></section><section class="detail-card books"><details><summary>Sportsbooks · '+e(books.length||g.bookmakerCount||0)+' ›</summary>'+(books.length?'<table>'+books.map(function(b){return '<tr><td>'+e(b.source)+'</td><td>'+e(signed(b.awaySpread))+'</td></tr>'}).join('')+'</table>':'<div class="notice">No book-level rows available.</div>')+'</details></section></main></div>'}
function render(){var app=document.getElementById('app');if(S.loading){app.innerHTML='<div class="loading">Loading the week…</div>';return}if(S.error){app.innerHTML='<div class="loading error">'+e(S.error)+'</div>';return}if(S.selected){app.innerHTML=detail()}else{app.innerHTML=S.tab==='games'?games():S.tab==='picks'?picks():S.tab==='tools'?tools():dashboard()}bind()}
function bind(){var app=document.getElementById('app');app.querySelectorAll('[data-tab]').forEach(function(b){b.onclick=function(){S.tab=b.getAttribute('data-tab');S.selected=null;if(S.tab==='picks'&&!S.pool)loadPool(S.week);render();if(S.tab==='tools')authStatus()}});app.querySelectorAll('[data-filter]').forEach(function(b){b.onclick=function(){S.filter=b.getAttribute('data-filter');render()}});app.querySelectorAll('[data-game]').forEach(function(b){b.onclick=function(){S.selected=b.getAttribute('data-game');render();scrollTo(0,0)}});var back=app.querySelector('[data-back]');if(back)back.onclick=function(){S.selected=null;render()};app.querySelectorAll('[data-week]').forEach(function(b){b.onclick=function(){loadPool(Math.max(1,Math.min(18,(S.picksWeek||S.week)+Number(b.getAttribute('data-week')))))}});app.querySelectorAll('[data-pick-game]').forEach(function(b){b.onclick=function(){savePick(b.getAttribute('data-pick-game'),b.getAttribute('data-team'))}});app.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var text=poolText(b.getAttribute('data-copy')==='compact'),p=app.querySelector('[data-preview]');if(p)p.textContent=text;if(navigator.clipboard)navigator.clipboard.writeText(text).catch(function(){})}});var unlock=app.querySelector('[data-unlock]');if(unlock)unlock.onclick=unlockAdmin;app.querySelectorAll('[data-action]').forEach(function(b){b.onclick=function(){runTool(b.getAttribute('data-action'))}})}
function loadPool(w){S.picksWeek=w;return json('/api/pool/outlooks?season='+encodeURIComponent(S.season)+'&week='+encodeURIComponent(w)).then(function(b){S.pool=b;render()}).catch(function(err){S.pool={games:[],error:err.message};render()})}
function savePick(id,team){json('/api/pool/picks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({season:S.season,week:S.picksWeek||S.week,gameId:id,team:team})}).then(function(){return loadPool(S.picksWeek||S.week)}).catch(function(err){alert(err.message+' — unlock Tools first.')})}
function authStatus(){json('/api/admin/session').then(function(b){var x=document.querySelector('[data-auth-state]');if(x)x.textContent=b.authenticated?'Unlocked':'Locked'}).catch(function(){})}
function unlockAdmin(){var pin=document.querySelector('[data-pin]');json('/api/admin/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin:pin&&pin.value})}).then(function(){authStatus()}).catch(function(err){alert(err.message)})}
function output(v){var x=document.querySelector('[data-output]');if(x)x.textContent=typeof v==='string'?v:JSON.stringify(v,null,2)}
function runTool(a){var map={integrity:['/api/results/integrity','GET'],usage:['/api/usage','GET'],context:['/api/context/sync','POST'],history:['/api/history/import','POST'],cache:['/api/cache/history/rebuild','POST']};output('Running…');if(a==='refresh'){json('/api/ingest/nfl/results',{method:'POST'}).then(function(scores){return json('/api/ingest/nfl',{method:'POST'}).then(function(market){return {scores:scores,market:market}})}).then(output).then(load).catch(function(err){output(err.message)});return}var cfg=map[a];json(cfg[0],{method:cfg[1]}).then(output).catch(function(err){output(err.message)})}
function load(){S.loading=true;render();Promise.all([json('/api/dashboard/nfl'),json('/api/focus/opportunities').catch(function(){return {games:[]}}),json('/api/data/freshness').catch(function(){return {state:'UNAVAILABLE'}})]).then(function(x){S.dashboard=x[0];S.focus=x[1];S.fresh=x[2];S.season=x[0].season;S.week=x[0].week;S.picksWeek=x[0].week;return loadPool(S.week)}).then(function(){S.loading=false;render()}).catch(function(err){S.loading=false;S.error=err.message;render()})}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(function(){});
load();
})();
</script>
</body></html>`;
}
