export const APP_VERSION = '0.22.0';

export function canonicalAppPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#080b10">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png">
<title>NFL Spread Tool</title>
<style>
:root{--bg:#080b10;--panel:#0e141c;--panel2:#111a23;--border:#233041;--text:#f4f7fb;--muted:#8c9aaa;--blue:#4ca6ff;--green:#72dc66;--yellow:#e1c45b;--red:#ef8e8e}
*{box-sizing:border-box}html,body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;overflow-x:hidden}button,input,select{font:inherit}.app{width:100%;max-width:560px;margin:0 auto;min-height:100vh;padding-bottom:82px;overflow-x:hidden}.topbar{padding:calc(13px + env(safe-area-inset-top)) 12px 10px;border-bottom:1px solid rgba(255,255,255,.07);position:sticky;top:0;z-index:10;background:rgba(8,11,16,.96);backdrop-filter:blur(16px)}.topline{display:flex;align-items:center;justify-content:space-between;gap:10px}.brand{font-size:13px;font-weight:950;letter-spacing:.055em}.brand-sub{font-size:9px;color:var(--muted);margin-top:3px;font-weight:700}.week-control{display:grid;grid-template-columns:31px minmax(92px,auto) 31px;gap:4px;align-items:center}.week-control button,.week-control select{height:31px;border:1px solid var(--border);background:var(--panel);color:var(--text);font-size:9px;font-weight:900}.week-control button{border-radius:9px}.week-control select{min-width:0;border-radius:9px;padding:0 6px;text-align:center}.week-note{font-size:8px;color:var(--muted);text-align:right;margin-top:4px}.content{padding:11px 12px 22px}.status{border:1px solid rgba(114,220,102,.22);background:#0d151b;border-radius:11px;padding:9px 10px;margin-bottom:11px}.status-top{display:flex;justify-content:space-between;gap:8px;font-size:9px;font-weight:900}.status-state{color:var(--green)}.status-sub{font-size:8px;color:var(--muted);margin-top:4px}.section{margin-bottom:15px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:10px;margin:0 2px 8px}.section-title{font-size:10px;font-weight:950;letter-spacing:.065em;text-transform:uppercase}.section-meta{font-size:9px;color:var(--muted);text-align:right}.empty,.notice{border:1px dashed var(--border);border-radius:13px;padding:15px;color:var(--muted);font-size:10px;line-height:1.5}.error{color:var(--red)}
.pulse{border:1px solid var(--border);background:var(--panel);border-radius:15px;padding:10px}.pulse-row{display:grid;grid-template-columns:82px repeat(3,minmax(0,1fr));gap:5px;align-items:stretch;padding:5px 0}.pulse-row+.pulse-row{border-top:1px solid rgba(255,255,255,.05)}.pulse-label{font-size:9px;font-weight:900;display:flex;align-items:center}.pulse-cell{min-width:0;border:1px solid rgba(255,255,255,.06);background:#0a1017;color:var(--muted);border-radius:8px;padding:7px 2px;text-align:center;cursor:pointer}.pulse-cell strong{display:block;color:var(--text);font-size:11px}.pulse-cell span{display:block;font-size:7px;margin-top:2px;white-space:normal}.pulse-cell.hot{border-color:rgba(114,220,102,.32);background:rgba(114,220,102,.07)}.pulse-cell.hot strong{color:var(--green)}.pulse-head{font-size:7px;color:var(--muted);text-align:center;text-transform:uppercase;align-self:end}
.focus-list{display:grid;gap:8px}.focus-row,.game-card{width:100%;text-align:left;color:var(--text);border:1px solid var(--border);background:var(--panel);border-radius:14px;cursor:pointer}.focus-row{display:grid;grid-template-columns:36px minmax(0,1fr) auto;gap:9px;align-items:start;padding:11px}.grade{width:32px;height:32px;border-radius:9px;display:grid;place-items:center;background:rgba(76,166,255,.13);color:var(--blue);font-size:14px;font-weight:950}.grade.a{color:var(--green);background:rgba(114,220,102,.1)}.focus-match{font-size:12px;font-weight:950}.focus-category{font-size:9px;color:var(--green);font-weight:850;margin-top:3px}.focus-market,.focus-evidence{font-size:8px;color:var(--muted);line-height:1.4;margin-top:4px}.focus-rate{font-size:15px;font-weight:950;color:var(--green);text-align:right}.focus-rate span{display:block;font-size:7px;color:var(--muted);margin-top:2px}.results-list{display:grid;gap:6px}.result-row{display:grid;grid-template-columns:1fr auto;gap:10px;border:1px solid var(--border);background:var(--panel);border-radius:11px;padding:9px;font-size:9px}.result-row strong{font-size:10px}.result-row span{color:var(--muted)}
.filters{display:flex;gap:6px;overflow:auto;margin-bottom:9px;padding-bottom:2px}.filter{border:1px solid var(--border);background:var(--panel);color:var(--muted);border-radius:999px;padding:7px 10px;font-size:9px;font-weight:850;white-space:nowrap}.filter.active{background:var(--blue);border-color:var(--blue);color:#06111b}.bucket-banner{display:flex;justify-content:space-between;align-items:center;gap:8px;border:1px solid rgba(76,166,255,.3);background:rgba(76,166,255,.07);border-radius:10px;padding:8px 10px;margin-bottom:9px;font-size:9px}.bucket-banner button{border:0;background:transparent;color:var(--blue);font-weight:900}.games{display:grid;gap:9px}.game-card{padding:12px}.game-top{display:grid;grid-template-columns:minmax(0,1fr) 58px minmax(0,1fr);align-items:start}.team{display:flex;gap:7px;align-items:center;min-width:0}.team.home{justify-content:flex-end;text-align:right}.team>div{min-width:0}.logo{width:32px;height:32px;object-fit:contain}.team-code{font-size:14px;font-weight:950}.team-name{font-size:7px;color:var(--muted);margin-top:1px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.team-market{font-size:9px;margin-top:4px;font-weight:850}.team-market .money{color:var(--muted)}.game-state{text-align:center;font-size:8px;font-weight:950;color:var(--muted);padding-top:6px;letter-spacing:.07em}.game-state.live{color:var(--green)}.score{font-size:27px;font-weight:950;margin-top:4px}.score.loser{color:#98a5b3}.kickoff{font-size:9px;color:var(--muted);text-align:center;margin:8px 0}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:9px}.metric{min-width:0;background:var(--panel2);border-radius:8px;padding:7px}.metric-label{font-size:7px;color:var(--muted);text-transform:uppercase}.metric-value{font-size:9px;font-weight:900;margin-top:3px;overflow-wrap:anywhere}.primary{color:var(--blue)}.signal{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:8px;margin-top:8px;padding:8px;border:1px solid rgba(76,166,255,.22);background:rgba(76,166,255,.06);border-radius:9px}.signal-label{font-size:7px;color:var(--muted);font-weight:900}.signal-value{font-size:10px;font-weight:950;text-align:center}.signal-meta{font-size:8px;color:var(--muted);white-space:nowrap}.market-move{display:flex;justify-content:space-between;gap:8px;border-top:1px solid rgba(255,255,255,.06);margin-top:8px;padding-top:8px;font-size:8px;color:var(--muted)}.market-move strong{color:var(--yellow);font-size:8px}.evidence-line{font-size:8px;color:var(--muted);margin-top:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.pick-summary{border:1px solid var(--border);background:var(--panel);border-radius:13px;padding:11px;display:flex;justify-content:space-between;align-items:center}.pick-summary strong{font-size:12px}.pick-summary span{font-size:9px;color:var(--muted)}.link-btn{border:0;background:transparent;color:var(--blue);font-size:10px;font-weight:900}.pick-game{border:1px solid var(--border);background:var(--panel);border-radius:14px;padding:11px;margin-bottom:8px}.pick-match{font-size:9px;color:var(--muted);text-align:center;margin-bottom:7px}.pick-options{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:7px}.pick-team{min-width:0;border:1px solid var(--border);background:#0a1017;color:var(--text);border-radius:11px;padding:10px;text-align:left}.pick-team.selected{border-color:var(--blue);background:rgba(76,166,255,.1)}.pick-team.winner{border-color:var(--green)}.pick-team.wrong{border-color:var(--red)}.pick-team strong{display:block;font-size:12px}.pick-team span{font-size:8px;color:var(--muted)}.pick-result{font-size:8px;font-weight:900;text-align:center;margin-top:8px}.pick-result.correct{color:var(--green)}.pick-result.wrong{color:var(--red)}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.action{border:1px solid var(--border);background:var(--panel2);color:var(--text);border-radius:11px;padding:10px;font-size:9px;font-weight:900}.action.primary{background:var(--blue);color:#06111b;border-color:var(--blue)}.copy-preview{white-space:pre-wrap;border:1px solid var(--border);background:#090e14;color:#bdc8d2;border-radius:11px;padding:10px;margin-top:8px;font:10px/1.5 ui-monospace,monospace}
.tools-intro{border:1px solid rgba(76,166,255,.28);background:rgba(76,166,255,.07);border-radius:14px;padding:13px;margin-bottom:11px}.tools-intro strong{font-size:12px}.tools-intro p{font-size:9px;color:var(--muted);line-height:1.45;margin:5px 0 0}.admin-row{display:flex;gap:7px}.admin-row input{min-width:0;flex:1;border:1px solid var(--border);background:#090e14;color:var(--text);border-radius:10px;padding:10px}.tool-list{display:grid;gap:7px}.tool{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:12px;padding:11px;text-align:left}.tool strong{display:block;font-size:10px}.tool span{display:block;font-size:8px;color:var(--muted);margin-top:3px}.tool.secondary{opacity:.82}.tool-output{white-space:pre-wrap;max-height:260px;overflow:auto;border:1px solid var(--border);background:#090e14;color:#bdc8d2;border-radius:11px;padding:10px;font:9px/1.45 ui-monospace,monospace}
.detail-head{display:grid;grid-template-columns:38px 1fr 38px;align-items:center;padding:calc(12px + env(safe-area-inset-top)) 9px 11px;border-bottom:1px solid rgba(255,255,255,.07);position:sticky;top:0;background:rgba(8,11,16,.96);z-index:12}.back{border:0;background:transparent;color:var(--text);font-size:28px}.detail-title{text-align:center;font-size:13px;font-weight:950}.hero{text-align:center;padding:16px 12px 8px}.hero-score{font-size:31px;font-weight:950}.hero-state{font-size:9px;color:var(--green);font-weight:900;margin-bottom:4px}.detail-card{border:1px solid var(--border);background:var(--panel);border-radius:14px;padding:12px;margin-bottom:9px}.detail-card h3{font-size:9px;letter-spacing:.06em;text-transform:uppercase;margin:0 0 9px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.detail-box{min-width:0;background:var(--panel2);border-radius:9px;padding:8px}.detail-box span{display:block;color:var(--muted);font-size:7px;text-transform:uppercase}.detail-box strong{display:block;font-size:10px;margin-top:2px;overflow-wrap:anywhere}.market-teams{display:grid;grid-template-columns:1fr 1fr;gap:7px}.market-team{background:var(--panel2);border-radius:9px;padding:9px}.market-team:last-child{text-align:right}.market-team strong{font-size:12px}.market-team span{display:block;color:var(--muted);font-size:8px;margin-top:3px}.readout{display:grid;gap:6px}.read-row{display:grid;grid-template-columns:76px minmax(0,1fr);gap:8px;font-size:9px;line-height:1.45}.read-row span{color:var(--muted)}.evidence-list{display:grid;gap:6px}.evidence-item{border-left:2px solid var(--border);padding-left:8px;font-size:9px;line-height:1.45}.evidence-item.support{border-color:var(--green)}.evidence-item.conflict{border-color:var(--yellow)}.evidence-item span{display:block;color:var(--muted);font-size:8px}.books summary{cursor:pointer;font-size:9px;font-weight:900}.books table{width:100%;font-size:9px;margin-top:9px;border-collapse:collapse}.books td{padding:6px;border-top:1px solid rgba(255,255,255,.05);text-align:right}.books td:first-child{text-align:left}
.bottom-nav{position:fixed;left:50%;bottom:0;transform:translateX(-50%);width:100%;max-width:560px;z-index:30;display:grid;grid-template-columns:repeat(4,1fr);padding:7px 7px calc(7px + env(safe-area-inset-bottom));background:rgba(7,10,14,.96);border-top:1px solid rgba(255,255,255,.08);backdrop-filter:blur(18px)}.nav{border:0;background:transparent;color:#718091;padding:6px 3px}.nav.active{color:var(--blue)}.nav-icon{display:block;font-size:18px}.nav-label{display:block;font-size:9px;font-weight:850;margin-top:3px}.loading{padding:80px 20px;text-align:center;color:var(--muted)}
</style>
</head>
<body><div id="app" class="app"><div class="loading">Loading the week…</div></div>
<script>
(function(){
'use strict';
var VERSION='0.22.0';
var params=new URLSearchParams(location.search),requestedTab=params.get('tab'),requestedWeek=Number(params.get('week'));
var S={tab:['dashboard','games','picks','tools'].indexOf(requestedTab)>=0?requestedTab:'dashboard',dashboard:null,focus:null,pool:null,fresh:null,selected:null,filter:'ALL',bucketFilter:null,season:null,week:null,activeWeek:null,loading:true,error:null};
var TEAM={'Arizona Cardinals':'ARI','Atlanta Falcons':'ATL','Baltimore Ravens':'BAL','Buffalo Bills':'BUF','Carolina Panthers':'CAR','Chicago Bears':'CHI','Cincinnati Bengals':'CIN','Cleveland Browns':'CLE','Dallas Cowboys':'DAL','Denver Broncos':'DEN','Detroit Lions':'DET','Green Bay Packers':'GB','Houston Texans':'HOU','Indianapolis Colts':'IND','Jacksonville Jaguars':'JAX','Kansas City Chiefs':'KC','Las Vegas Raiders':'LV','Los Angeles Chargers':'LAC','Los Angeles Rams':'LAR','Miami Dolphins':'MIA','Minnesota Vikings':'MIN','New England Patriots':'NE','New Orleans Saints':'NO','New York Giants':'NYG','New York Jets':'NYJ','Philadelphia Eagles':'PHI','Pittsburgh Steelers':'PIT','San Francisco 49ers':'SF','Seattle Seahawks':'SEA','Tampa Bay Buccaneers':'TB','Tennessee Titans':'TEN','Washington Commanders':'WAS'};
function e(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function num(v){if(v===null||v===undefined||v==='')return null;var n=Number(v);return Number.isFinite(n)?n:null}
function code(n){return TEAM[n]||String(n||'NFL').split(/\\s+/).map(function(x){return x[0]}).join('').slice(0,3).toUpperCase()}
function logo(n){var slug=code(n).toLowerCase();if(slug==='was')slug='wsh';return 'https://a.espncdn.com/i/teamlogos/nfl/500/'+slug+'.png'}
function signed(v){var n=num(v);return n===null?'—':n===0?'PK':(n>0?'+':'')+n}
function pct(v){var n=num(v);if(n===null)return '—';return (Math.abs(n)<=1?Math.round(n*1000)/10:Math.round(n*10)/10)+'%'}
function ml(v){var n=num(v);return n===null?'—':(n>0?'+':'')+Math.round(n)}
function tier(t){return t==='LE_3'||t==='<=3'?'0.5–3':t==='LE_7'||t==='<=7'?'3.5–7':t==='GT_7'||t==='>7'?'7.5+':t==='PICK_EM'?'PK':t||'—'}
function cls(v){return String(v||'').replace('AwayFavorite','Away Favorite').replace('HomeFavorite','Home Favorite').replace('AwayUnderdog','Away Dog').replace('HomeUnderdog','Home Dog').replace('AwayFav','Away Favorite').replace('HomeFav','Home Favorite')||'—'}
function kickoff(v){if(!v)return 'Kickoff unavailable';var d=new Date(v);return d.toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function json(path,opt){return fetch(path,Object.assign({cache:'no-store',credentials:'same-origin',headers:{accept:'application/json'}},opt||{})).then(function(r){return r.json().catch(function(){return {error:'Invalid response'}}).then(function(b){if(!r.ok)throw new Error(b.message||b.error||'Request failed');return b})})}
function q(path){return path+'?season='+encodeURIComponent(S.season)+'&week='+encodeURIComponent(S.week)}
function syncUrl(){var p=new URLSearchParams();if(S.tab!=='dashboard')p.set('tab',S.tab);if(S.week&&S.week!==S.activeWeek)p.set('week',S.week);history.replaceState(null,'',p.toString()?'/?'+p.toString():'/')}
function weekControl(){var options='';for(var i=1;i<=18;i++)options+='<option value="'+i+'" '+(i===S.week?'selected':'')+'>WEEK '+i+(i===S.activeWeek?' · LIVE':'')+'</option>';return '<div><div class="week-control"><button data-week-change="-1" aria-label="Previous week">‹</button><select data-week-select aria-label="Select week">'+options+'</select><button data-week-change="1" aria-label="Next week">›</button></div><div class="week-note">'+(S.week===S.activeWeek?'Current actionable week':'Viewing full schedule')+'</div></div>'}
function header(){return '<header class="topbar"><div class="topline"><div><div class="brand">NFL SPREAD TOOL</div><div class="brand-sub">Category · tier · market · evidence</div></div>'+weekControl()+'</div></header>'}
function nav(){return '<nav class="bottom-nav">'+[['dashboard','⌂','Dashboard'],['games','▦','Games'],['picks','✓','Picks'],['tools','⚙','Tools']].map(function(x){return '<button class="nav '+(S.tab===x[0]?'active':'')+'" data-tab="'+x[0]+'"><span class="nav-icon">'+x[1]+'</span><span class="nav-label">'+x[2]+'</span></button>'}).join('')+'</nav>'}
function status(){var f=S.fresh||{},state=f.overallState||f.state||'CURRENT',r=S.dashboard&&S.dashboard.results,n=S.dashboard&&S.dashboard.currentSeasonGamesConsidered;return '<div class="status"><div class="status-top"><span>DATA STATUS</span><span class="status-state">'+e(state)+'</span></div><div class="status-sub">'+e(r?r.completedGames+' completed · '+r.awaitingCompletion+' awaiting completion':'Schedule loaded')+(n!=null?' · Tier records through '+e(n)+' completed games':'')+'</div></div>'}
function gameState(g){if(g.final)return 'FINAL';if(g.live)return 'LIVE';return 'UPCOMING'}
function spreadOf(g){return g.spread||{away:g.medianAwaySpread,home:g.medianHomeSpread,projectedTeam:g.projectedTeam,coverRate:g.projectedCoverRate,grade:g.grade,sampleSize:g.sampleSize,status:g.projectionStatus}}
function marketOf(g){var m=g.market||g.moneyline||{};return {awayMoneyline:m.awayMoneyline!=null?m.awayMoneyline:m.consensusAwayMoneyline,homeMoneyline:m.homeMoneyline!=null?m.homeMoneyline:m.consensusHomeMoneyline,awayWinPct:m.awayWinPct!=null?m.awayWinPct:m.awayWinProbability,homeWinPct:m.homeWinPct!=null?m.homeWinPct:m.homeWinProbability,books:m.books||[]}}
function mergedGames(){var dash=S.dashboard&&S.dashboard.games||[],pool=S.pool&&S.pool.games||[],focus=S.focus&&S.focus.games||[],pBy={},fBy={};pool.forEach(function(g){pBy[String(g.gameId)]=g});focus.forEach(function(g){fBy[String(g.gameId)]=g});return dash.map(function(g){var p=pBy[String(g.id)]||{},s=p.spread||spreadOf(g);return Object.assign({},g,p,{id:g.id,spread:s,market:p.market||marketOf(g),movement:p.movement||null,history:p.history||null,context:p.context||null,outlook:p.outlook||null,brain:fBy[String(g.id)]||null,classification:g.classification||p.classification||null,projectedTeam:s.projectedTeam||g.projectedTeam,projectedCoverRate:s.coverRate!=null?s.coverRate:g.projectedCoverRate,sampleSize:s.sampleSize!=null?s.sampleSize:g.sampleSize,grade:s.grade||g.grade,projectionStatus:s.status||g.projectionStatus,final:g.final||p.final,postgame:g.postgame||null})})}
function classificationFor(g,side){return g.classification&&g.classification[side]}
function projectedClass(g){if(g.projectedClassification)return g.projectedClassification;var side=g.projectedTeam===g.awayTeam?'away':g.projectedTeam===g.homeTeam?'home':null;return side?classificationFor(g,side):null}
function record(b){if(!b)return 'n=0';return Number(b.wins||0)+'-'+Number(b.losses||0)+(Number(b.pushes||0)?'-'+Number(b.pushes||0):'')}
function projectedBucket(g){var side=g.projectedTeam===g.awayTeam?'away':g.projectedTeam===g.homeTeam?'home':null;return side&&g.currentSeasonStats?g.currentSeasonStats[side]:null}
function bucket(name,t){var b=S.dashboard&&S.dashboard.liveWeekStats&&S.dashboard.liveWeekStats.buckets&&S.dashboard.liveWeekStats.buckets[name+'|'+t];if(!b)return null;var w=Number(b.wins||0),l=Number(b.losses||0),p=Number(b.pushes||0),n=w+l;return {rate:b.coverRate==null?(n?Math.round(w/n*1000)/10:null):b.coverRate,record:w+'-'+l+(p?'-'+p:'')}}
function bucketGames(name,t){return mergedGames().filter(function(g){return g.classification&&g.classification.tier===t&&(g.classification.away===name||g.classification.home===name)})}
function pulse(){var rows=[['Away Dog','AwayDog'],['Away Favorite','AwayFav'],['Home Dog','HomeDog'],['Home Favorite','HomeFav']],ts=[['0.5–3','<=3'],['3.5–7','<=7'],['7.5+','>7']];return '<section class="section"><div class="section-head"><div class="section-title">Tier Pulse</div><div class="section-meta">Current season · tap to see W'+e(S.week)+' games</div></div><div class="pulse"><div class="pulse-row"><div></div>'+ts.map(function(t){return '<div class="pulse-head">'+t[0]+'</div>'}).join('')+'</div>'+rows.map(function(r){return '<div class="pulse-row"><div class="pulse-label">'+r[0]+'</div>'+ts.map(function(t){var b=bucket(r[1],t[1]),count=bucketGames(r[1],t[1]).length,hot=b&&Number(b.rate)>=55;return '<button class="pulse-cell '+(hot?'hot':'')+'" data-bucket="'+r[1]+'|'+t[1]+'"><strong>'+(b&&b.rate!=null?e(b.rate)+'%':'—')+'</strong><span>'+(b?e(b.record):'n=0')+' · '+count+' W'+e(S.week)+' game'+(count===1?'':'s')+'</span></button>'}).join('')+'</div>'}).join('')+'</div></section>'}
function strategy(g){var b=g.brain||{},x=String(b.bestUse||'');if(x.indexOf('SPREAD +')>=0)return 'Spread + outright';if(x.indexOf('SPREAD')>=0)return 'Spread';if(x.indexOf('POOL')>=0||x.indexOf('OUTRIGHT')>=0||x.indexOf('SURVIVOR')>=0)return 'Outright pool';if(x.indexOf('WATCH')>=0)return 'Watch';return g.grade?'Spread':'Pass'}
function brainText(g){var b=g.brain;if(!b)return 'Tier signal available; supporting evidence not loaded.';var supports=Number(b.independentSignals||0),conflicts=(b.conflict||[]).length;return supports+' independent signal'+(supports===1?'':'s')+' support'+(supports===1?'s':'')+(conflicts?' · '+conflicts+' conflict'+(conflicts===1?'':'s'):' · no primary conflict')}
function contextText(g){var obs=g.context&&g.context.observations||[];if(!obs.length)return '';var x=obs.find(function(o){return o.kind==='supporting'||o.kind==='interesting'})||obs[0];return x.label+': '+x.detail}
function movementText(g){var m=g.movement;if(!m||num(m.firstCapturedAwaySpread)===null)return 'Line history unavailable';var final=gameState(g)==='FINAL',end=final&&num(m.closingAwaySpread)!==null?m.closingAwaySpread:m.currentAwaySpread,label=final?'Close':'Current';if(num(end)===null)return 'Open '+code(g.awayTeam)+' '+signed(m.firstCapturedAwaySpread)+' · current unavailable';return 'Open '+code(g.awayTeam)+' '+signed(m.firstCapturedAwaySpread)+' → '+label+' '+code(g.awayTeam)+' '+signed(end)}
function movementDelta(g){var m=g.movement,mag=m&&num(m.movementMagnitude);if(mag===null)return '';if(mag===0)return 'No movement';var toward=m.direction==='TOWARD_AWAY'?code(g.awayTeam):m.direction==='TOWARD_HOME'?code(g.homeTeam):'';return mag+' pt'+(mag===1?'':'s')+(toward?' toward '+toward:'')}
function focusGames(){var order={A:3,B:2,C:1};return mergedGames().filter(function(g){return !g.final&&['A','B','C'].indexOf(g.grade)>=0&&num(g.projectedCoverRate)>=55}).sort(function(a,b){return order[b.grade]-order[a.grade]||num(b.projectedCoverRate)-num(a.projectedCoverRate)||String(a.kickoffAt).localeCompare(String(b.kickoffAt))})}
function focus(){var list=focusGames();return '<section class="section"><div class="section-head"><div class="section-title">Focus This Week</div><div class="section-meta">'+list.length+' qualifying game'+(list.length===1?'':'s')+'</div></div>'+(list.length?'<div class="focus-list">'+list.map(function(g){var s=spreadOf(g),m=marketOf(g),b=projectedBucket(g),isAway=g.projectedTeam===g.awayTeam,line=isAway?s.away:s.home,price=isAway?m.awayMoneyline:m.homeMoneyline;return '<button class="focus-row" data-game="'+e(g.id)+'"><span class="grade '+String(g.grade).toLowerCase()+'">'+e(g.grade)+'</span><span><div class="focus-match">'+e(code(g.awayTeam))+' @ '+e(code(g.homeTeam))+' · '+e(code(g.projectedTeam))+' '+e(signed(line))+'</div><div class="focus-category">'+e(cls(projectedClass(g)))+' · '+e(tier(g.classification&&g.classification.tier))+'</div><div class="focus-market">ML '+e(ml(price))+' · '+e(movementText(g))+'</div><div class="focus-evidence">Strategy: '+e(strategy(g))+' · '+e(brainText(g))+(contextText(g)?' · '+e(contextText(g)):'')+'</div></span><span class="focus-rate">'+e(pct(g.projectedCoverRate))+'<span>'+e(record(b))+' · n='+e(g.sampleSize||0)+'</span></span></button>'}).join('')+'</div>':'<div class="empty">No upcoming games currently meet the 55% Focus threshold for Week '+e(S.week)+'. Games without a posted line remain unclassified.</div>')+'</section>'}
function resultsSummary(){var list=mergedGames().filter(function(g){return g.final&&g.grade});if(!list.length)return '';return '<section class="section"><div class="section-head"><div class="section-title">Focus Results</div><div class="section-meta">Original qualified games</div></div><div class="results-list">'+list.slice(0,4).map(function(g){var result=g.postgame?(g.postgame.spreadResult==='PUSH'?'PUSH':code(g.postgame.coveringTeam)+' COVERED'):'Final';return '<button class="result-row" data-game="'+e(g.id)+'"><span><strong>'+e(g.grade)+' · '+e(code(g.awayTeam))+' @ '+e(code(g.homeTeam))+'</strong><br>'+e(cls(projectedClass(g)))+' · '+e(tier(g.classification&&g.classification.tier))+' · '+e(pct(g.projectedCoverRate))+'</span><strong>'+e(result)+'</strong></button>'}).join('')+'</div></section>'}
function pickSummary(){var p=S.pool||{},games=p.games||[],picked=games.filter(function(g){return g.pick}).length;return '<section class="section"><div class="section-head"><div class="section-title">Your Picks</div><div class="section-meta">Week '+e(S.week)+'</div></div><div class="pick-summary"><div><strong>'+picked+' of '+games.length+' selected</strong><br><span>'+e(p.summary&&p.summary.correct||0)+' correct · '+e(p.summary&&p.summary.wrong||0)+' wrong</span></div><button class="link-btn" data-tab="picks">Open Picks ›</button></div></section>'}
function filterGames(games){if(S.bucketFilter){var p=S.bucketFilter.split('|'),name=p[0],t=p[1];return games.filter(function(g){return g.classification&&g.classification.tier===t&&(g.classification.away===name||g.classification.home===name)})}if(S.filter==='FOCUS')return games.filter(function(g){return ['A','B','C'].indexOf(g.grade)>=0});if(S.filter!=='ALL')return games.filter(function(g){return g.grade===S.filter});return games}
function filters(){var games=mergedGames();return '<div class="filters">'+['ALL','FOCUS','A','B','C'].map(function(f){var count=f==='ALL'?games.length:f==='FOCUS'?games.filter(function(g){return ['A','B','C'].indexOf(g.grade)>=0}).length:games.filter(function(g){return g.grade===f}).length;return '<button class="filter '+(!S.bucketFilter&&S.filter===f?'active':'')+'" data-filter="'+f+'">'+(f==='FOCUS'?'Focus':f)+' '+count+'</button>'}).join('')+'</div>'}
function teamBlock(g,away,a,h){var s=spreadOf(g),m=marketOf(g),team=away?g.awayTeam:g.homeTeam,spread=away?s.away:s.home,price=away?m.awayMoneyline:m.homeMoneyline,score=away?a:h,other=away?h:a;return '<div class="team '+(away?'':'home')+'">'+(away?'<img class="logo" alt="" src="'+e(logo(team))+'">':'')+'<div><div class="team-code">'+e(code(team))+'</div><div class="team-name">'+e(team)+'</div><div class="team-market">'+e(signed(spread))+' <span class="money">· ML '+e(ml(price))+'</span></div>'+(score!=null?'<div class="score '+(Number(score)<Number(other)?'loser':'')+'">'+e(score)+'</div>':'')+'</div>'+(!away?'<img class="logo" alt="" src="'+e(logo(team))+'">':'')+'</div>'}
function gameCard(g){var st=gameState(g),a=g.final?g.final.awayScore:g.live&&g.live.awayScore,h=g.final?g.final.homeScore:g.live&&g.live.homeScore,post=g.postgame,b=post&&post.liveBucket,pb=projectedBucket(g),signal=st==='FINAL'?(post?(post.spreadResult==='PUSH'?'PUSH':code(post.coveringTeam)+' COVERED'):'FINAL'):(g.projectedTeam?code(g.projectedTeam)+' · '+pct(g.projectedCoverRate):'No tier edge yet'),meta=st==='FINAL'?(b?record(b)+' · '+pct(b.coverRate):'Result stored'):(g.grade?g.grade+' · '+record(pb)+' · n='+e(g.sampleSize||0):'Not Focus');return '<button class="game-card" data-game="'+e(g.id)+'"><div class="game-top">'+teamBlock(g,true,a,h)+'<div class="game-state '+(st==='LIVE'?'live':'')+'">'+st+'</div>'+teamBlock(g,false,a,h)+'</div>'+(st==='UPCOMING'?'<div class="kickoff">'+e(kickoff(g.kickoffAt))+'</div>':'')+'<div class="metrics"><div class="metric"><div class="metric-label">Category</div><div class="metric-value primary">'+e(cls(g.classification&&g.classification.away))+' / '+e(cls(g.classification&&g.classification.home))+'</div></div><div class="metric"><div class="metric-label">Tier</div><div class="metric-value">'+e(tier(g.classification&&g.classification.tier))+'</div></div></div><div class="signal"><span class="signal-label">'+(st==='FINAL'?'FINAL SPREAD RESULT':'TIER EDGE')+'</span><strong class="signal-value">'+e(signal)+'</strong><span class="signal-meta">'+e(meta)+'</span></div><div class="market-move"><span>'+e(movementText(g))+'</span><strong>'+e(movementDelta(g))+'</strong></div>'+(contextText(g)?'<div class="evidence-line">Context · '+e(contextText(g))+'</div>':'')+'</button>'}
function bucketLabel(){if(!S.bucketFilter)return '';var p=S.bucketFilter.split('|');return cls(p[0])+' · '+tier(p[1])}
function gamesSection(){var games=filterGames(mergedGames());return '<section class="section"><div class="section-head"><div class="section-title">All Games</div><div class="section-meta">Week '+e(S.week)+' · '+games.length+' shown</div></div>'+filters()+(S.bucketFilter?'<div class="bucket-banner"><strong>'+e(bucketLabel())+'</strong><button data-clear-bucket>Clear filter ×</button></div>':'')+'<div class="games">'+(games.length?games.map(gameCard).join(''):'<div class="empty">No Week '+e(S.week)+' games match this filter.</div>')+'</div></section>'}
function dashboard(){return header()+'<main class="content">'+status()+pulse()+focus()+resultsSummary()+pickSummary()+'</main>'+nav()}
function games(){return header()+'<main class="content">'+status()+gamesSection()+'</main>'+nav()}
function poolText(compact){var p=S.pool||{},lines=['Week '+S.week+' Picks'];(p.games||[]).filter(function(g){return g.pick}).forEach(function(g){var away=g.pick===g.awayTeam,m=away?g.market.awayMoneyline:g.market.homeMoneyline,w=away?g.market.awayWinPct:g.market.homeWinPct;lines.push(compact?code(g.pick)+' ('+ml(m)+', '+pct(w)+')':code(g.pick)+' — ML '+ml(m)+' · '+pct(w)+' market win')});return compact?lines[0]+':\\n'+lines.slice(1).join(', '):lines.join('\\n')}
function pickGame(g){function option(team,isAway){var selected=g.pick===team,result=selected&&g.pickResult,m=isAway?g.market.awayMoneyline:g.market.homeMoneyline,w=isAway?g.market.awayWinPct:g.market.homeWinPct;return '<button class="pick-team '+(selected?'selected ':'')+(result==='CORRECT'?'winner':result==='WRONG'?'wrong':'')+'" data-pick-game="'+e(g.gameId)+'" data-team="'+e(team)+'"><strong>'+e(code(team))+'</strong><span>ML '+e(ml(m))+' · '+e(pct(w))+' market</span></button>'}return '<div class="pick-game"><div class="pick-match">'+e(kickoff(g.kickoffAt))+'</div><div class="pick-options">'+option(g.awayTeam,true)+option(g.homeTeam,false)+'</div>'+(g.pickResult?'<div class="pick-result '+e(String(g.pickResult).toLowerCase())+'">'+e(g.pickResult)+'</div>':'')+'</div>'}
function picks(){var p=S.pool||{},games=p.games||[],done=games.length&&games.every(function(g){return g.final}),selected=games.filter(function(g){return g.pick}).length;return header()+'<main class="content"><section class="section"><div class="section-head"><div class="section-title">'+(done?'Results':'Weekly Picks')+'</div><div class="section-meta">'+selected+'/'+games.length+' selected</div></div>'+games.map(pickGame).join('')+'<div class="actions"><button class="action primary" data-copy="detail">Copy Detailed</button><button class="action" data-copy="compact">Copy Compact</button></div><div class="copy-preview" data-preview>'+e(poolText(false))+'</div></section></main>'+nav()}
function tool(action,name,desc,secondary){return '<button class="tool '+(secondary?'secondary':'')+'" data-action="'+action+'"><span><strong>'+name+'</strong><span>'+desc+'</span></span><b>›</b></button>'}
function tools(){return header()+'<main class="content">'+status()+'<div class="tools-intro"><strong>Tools & Admin</strong><p>Routine checks are automatic. Manual controls are available for recovery and verification.</p></div><section class="section"><div class="section-head"><div class="section-title">Admin Session</div><div class="section-meta" data-auth-state>Checking…</div></div><div class="admin-row"><input type="password" data-pin placeholder="Enter PIN"><button class="action primary" data-unlock>Unlock</button></div></section><section class="section"><div class="section-head"><div class="section-title">Manual Actions</div></div><div class="tool-list">'+tool('refresh','Refresh Game Data','Scores first, then current spreads and moneylines',false)+tool('integrity','Results Integrity','Verify completed games and missing finals',false)+tool('usage','API Usage','Review provider calls and remaining credits',false)+tool('context','Update Context','Refresh weather, rest and schedule context',true)+tool('history','Load Historical Data','Import the historical reference dataset',true)+tool('cache','Build History Cache','Rebuild stored weekly summaries',true)+'</div></section><section class="section"><div class="section-head"><div class="section-title">Output</div><div class="section-meta">v'+VERSION+'</div></div><div class="tool-output" data-output>Ready.</div></section></main>'+nav()}
function historyItems(g){var out=[];['away','home'].forEach(function(side){var h=g.history&&g.history[side],team=side==='away'?g.awayTeam:g.homeTeam;(h&&h.notable||[]).forEach(function(x){var metric=num(x.coverPct)!==null?pct(x.coverPct)+' ATS':num(x.winPct)!==null?pct(x.winPct)+' outright':'record unavailable';out.push({team:team,label:x.label,metric:metric,games:x.games})})});return out.slice(0,5)}
function contextItems(g){return (g.context&&g.context.observations||[]).slice(0,5)}
function evidence(g){var hist=historyItems(g),ctx=contextItems(g),team=g.projectedTeam;return '<section class="detail-card"><h3>Historical Evidence</h3>'+(hist.length?'<div class="evidence-list">'+hist.map(function(x){var support=x.team===team;return '<div class="evidence-item '+(support?'support':'')+'"><strong>'+e(code(x.team))+' · '+e(x.label)+'</strong><span>'+e(x.metric)+' · '+e(x.games)+' games · 2015–2025</span></div>'}).join('')+'</div>':'<div class="notice">No relevant historical split is available for this matchup.</div>')+'</section><section class="detail-card"><h3>Context</h3>'+(ctx.length?'<div class="evidence-list">'+ctx.map(function(x){var side=x.side==='AWAY'?g.awayTeam:x.side==='HOME'?g.homeTeam:null,support=side&&side===team,conflict=side&&team&&side!==team;return '<div class="evidence-item '+(support?'support':conflict?'conflict':'')+'"><strong>'+e((support?'Supports '+code(team):conflict?'Conflicts · '+code(side):x.kind==='neutral'?'Neutral':'Notice')+' · '+x.label)+'</strong><span>'+e(x.detail)+'</span></div>'}).join('')+'</div>':'<div class="notice">No notable contextual condition is loaded.</div>')+'</section>'}
function booksTable(g){var spreadBooks=g.books||[],moneyBooks=marketOf(g).books||[],map={};spreadBooks.forEach(function(x){map[x.source]={source:x.source,spread:x.awaySpread}});moneyBooks.forEach(function(x){map[x.source]=Object.assign(map[x.source]||{source:x.source},{awayMoneyline:x.awayMoneyline,homeMoneyline:x.homeMoneyline})});var rows=Object.keys(map).sort().map(function(k){return map[k]});return '<section class="detail-card books"><details><summary>Sportsbooks · '+e(rows.length||g.bookmakerCount||0)+' ›</summary>'+(rows.length?'<table><tr><td>Book</td><td>'+e(code(g.awayTeam))+' spread</td><td>ML</td><td>'+e(code(g.homeTeam))+' ML</td></tr>'+rows.map(function(b){return '<tr><td>'+e(b.source)+'</td><td>'+e(signed(b.spread))+'</td><td>'+e(ml(b.awayMoneyline))+'</td><td>'+e(ml(b.homeMoneyline))+'</td></tr>'}).join('')+'</table>':'<div class="notice">No book-level rows available.</div>')+'</details></section>'}
function detail(){var g=mergedGames().find(function(x){return String(x.id)===String(S.selected)});if(!g)return games();var st=gameState(g),post=g.postgame,s=spreadOf(g),m=marketOf(g),pb=projectedBucket(g),awayCurrent=s.away,homeCurrent=s.home;return '<div><header class="detail-head"><button class="back" data-back>‹</button><div class="detail-title">'+e(code(g.awayTeam))+' @ '+e(code(g.homeTeam))+' · W'+e(S.week)+'</div><div></div></header><div class="hero"><div class="hero-state">'+st+'</div><div class="hero-score">'+(g.final?e(g.final.awayScore)+'–'+e(g.final.homeScore):e(kickoff(g.kickoffAt)))+'</div></div><main class="content">'+(st==='FINAL'?'<section class="detail-card"><h3>Spread Result</h3><div class="signal-value">'+e(post?(post.spreadResult==='PUSH'?'PUSH':code(post.coveringTeam)+' COVERED'):'Final result stored')+'</div></section>':'')+'<section class="detail-card"><h3>'+(st==='FINAL'?'Closing Market':'Current Market')+'</h3><div class="market-teams"><div class="market-team"><strong>'+e(code(g.awayTeam))+' '+e(signed(awayCurrent))+'</strong><span>ML '+e(ml(m.awayMoneyline))+' · '+e(pct(m.awayWinPct))+' no-vig</span></div><div class="market-team"><strong>'+e(code(g.homeTeam))+' '+e(signed(homeCurrent))+'</strong><span>ML '+e(ml(m.homeMoneyline))+' · '+e(pct(m.homeWinPct))+' no-vig</span></div></div><div class="market-move"><span>'+e(movementText(g))+'</span><strong>'+e(movementDelta(g))+'</strong></div></section><section class="detail-card"><h3>Original Thesis</h3><div class="detail-grid"><div class="detail-box"><span>Our side</span><strong>'+e(g.projectedTeam?code(g.projectedTeam)+' · '+cls(projectedClass(g)):'No tier edge')+'</strong></div><div class="detail-box"><span>Tier</span><strong>'+e(tier(g.classification&&g.classification.tier))+'</strong></div><div class="detail-box"><span>Percentage</span><strong>'+e(pct(g.projectedCoverRate))+'</strong></div><div class="detail-box"><span>Record · Sample · Grade</span><strong>'+e(record(pb))+' · n='+e(g.sampleSize||0)+' · '+e(g.grade||'—')+'</strong></div></div></section><section class="detail-card"><h3>Expert Read</h3><div class="readout"><div class="read-row"><span>Strategy</span><strong>'+e(strategy(g))+'</strong></div><div class="read-row"><span>Brain</span><strong>'+e(brainText(g))+'</strong></div><div class="read-row"><span>Context</span><strong>'+e(contextText(g)||'No notable contextual condition')+'</strong></div></div></section>'+evidence(g)+booksTable(g)+'</main></div>'}
function render(){var app=document.getElementById('app');if(S.loading){app.innerHTML='<div class="loading">Loading Week '+e(S.week||'…')+'</div>';return}if(S.error){app.innerHTML='<div class="loading error">'+e(S.error)+'</div>';return}if(S.selected)app.innerHTML=detail();else app.innerHTML=S.tab==='games'?games():S.tab==='picks'?picks():S.tab==='tools'?tools():dashboard();bind()}
function changeWeek(w){w=Math.max(1,Math.min(18,Number(w)||S.week));if(w===S.week)return;S.selected=null;S.bucketFilter=null;S.filter='ALL';loadWeek(w)}
function bind(){var app=document.getElementById('app');app.querySelectorAll('[data-tab]').forEach(function(b){b.onclick=function(){S.tab=b.getAttribute('data-tab');S.selected=null;syncUrl();render();if(S.tab==='tools')authStatus()}});app.querySelectorAll('[data-week-change]').forEach(function(b){b.onclick=function(){changeWeek(S.week+Number(b.getAttribute('data-week-change')))}});var select=app.querySelector('[data-week-select]');if(select)select.onchange=function(){changeWeek(Number(select.value))};app.querySelectorAll('[data-filter]').forEach(function(b){b.onclick=function(){S.filter=b.getAttribute('data-filter');S.bucketFilter=null;render()}});app.querySelectorAll('[data-bucket]').forEach(function(b){b.onclick=function(){S.bucketFilter=b.getAttribute('data-bucket');S.filter='ALL';S.tab='games';syncUrl();render();scrollTo(0,0)}});var clear=app.querySelector('[data-clear-bucket]');if(clear)clear.onclick=function(){S.bucketFilter=null;render()};app.querySelectorAll('[data-game]').forEach(function(b){b.onclick=function(){S.selected=b.getAttribute('data-game');render();scrollTo(0,0)}});var back=app.querySelector('[data-back]');if(back)back.onclick=function(){S.selected=null;render()};app.querySelectorAll('[data-pick-game]').forEach(function(b){b.onclick=function(){savePick(b.getAttribute('data-pick-game'),b.getAttribute('data-team'))}});app.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var text=poolText(b.getAttribute('data-copy')==='compact'),p=app.querySelector('[data-preview]');if(p)p.textContent=text;if(navigator.clipboard)navigator.clipboard.writeText(text).catch(function(){})}});var unlock=app.querySelector('[data-unlock]');if(unlock)unlock.onclick=unlockAdmin;app.querySelectorAll('[data-action]').forEach(function(b){b.onclick=function(){runTool(b.getAttribute('data-action'))}})}
function savePick(id,team){json('/api/pool/picks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({season:S.season,week:S.week,gameId:id,team:team})}).then(function(){return loadWeek(S.week)}).catch(function(err){alert(err.message+' — unlock Tools first.')})}
function authStatus(){json('/api/admin/session').then(function(b){var x=document.querySelector('[data-auth-state]');if(x)x.textContent=b.authenticated?'Unlocked':'Locked'}).catch(function(){})}
function unlockAdmin(){var pin=document.querySelector('[data-pin]');json('/api/admin/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin:pin&&pin.value})}).then(function(){authStatus()}).catch(function(err){alert(err.message)})}
function output(v){var x=document.querySelector('[data-output]');if(x)x.textContent=typeof v==='string'?v:JSON.stringify(v,null,2)}
function runTool(a){var map={integrity:['/api/results/integrity','GET'],usage:['/api/usage','GET'],context:['/api/context/sync','POST'],history:['/api/history/import','POST'],cache:['/api/cache/history/rebuild','POST']};output('Running…');if(a==='refresh'){json('/api/ingest/nfl/results',{method:'POST'}).then(function(scores){return json('/api/ingest/nfl',{method:'POST'}).then(function(market){return {scores:scores,market:market}})}).then(output).then(function(){return loadWeek(S.week)}).catch(function(err){output(err.message)});return}var cfg=map[a];json(cfg[0],{method:cfg[1]}).then(output).catch(function(err){output(err.message)})}
function loadWeek(w){S.week=w;S.loading=true;S.error=null;syncUrl();render();return Promise.all([json(q('/api/dashboard/nfl')),json(q('/api/pool/outlooks')).catch(function(){return {games:[],summary:{}}}),json(q('/api/focus/opportunities')).catch(function(){return {games:[]}}),json(q('/api/data/freshness')).catch(function(){return {state:'UNAVAILABLE'}})]).then(function(x){S.dashboard=x[0];S.pool=x[1];S.focus=x[2];S.fresh=x[3];S.loading=false;render()}).catch(function(err){S.loading=false;S.error=err.message;render()})}
function load(){S.loading=true;render();json('/api/dashboard/nfl').then(function(d){S.season=d.season;S.activeWeek=d.week;var w=Number.isInteger(requestedWeek)&&requestedWeek>=1&&requestedWeek<=18?requestedWeek:d.week;return loadWeek(w)}).catch(function(err){S.loading=false;S.error=err.message;render()})}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(function(){});
load();
})();
</script>
</body></html>`;
}
